### ISSUE TITLE
Build Errors and Notifications

### ISSUE THREAD

**Issue by mwhelanmachship** [fluxcd/flux2#731] opened 2021-01-18 05:27 UTC
Hi,

I've configured flux and have started testing before adding to production. 
I've also setup error notifications for Slack.

I'm testing error messages at the moment through Slack.
When a build fails, we get about 10-20 error messages initially when the build fails and then an error every minute or so after that.

Is it possible to reduce the number of errors initially received to Slack and also set the number of times the build tries to redeploy?

Thanks for your help,
Mark

**Comment by stefanprodan** [comment] 2021-01-19 10:09
Duplicate of: https://github.com/fluxcd/notification-controller/issues/76

**Closed by stefanprodan** 2021-01-19 10:09 UTC
