### ISSUE TITLE
Issues with source-controller deployments when installing on OpenShift

### ISSUE THREAD

**Issue by joeslow** [fluxcd/flux2#1210] opened 2021-04-05 16:44 UTC
### Describe the bug

After following the 'Get started' instructions a namespace with the flux controllers is successfully created - alas the pod of the source-controller deployment is never created. Error message is
```yaml
message: >-
        pods "source-controller-546f697b96-" is forbidden: unable to validate
        against any security context constraint: [fsGroup: Invalid value:
        []int64{1337}: 1337 is not an allowed group]
```
If I edit the source-controller deployment resource and replace the fsgroup value with the value of the openshift.io/sa.scc.supplemental-groups annotation of the flux-system namespace resource the pod gets created and runs until the deployment resource is reconciled and set-back to the original value of 1337. Strangely this doesn't seem to be a problem with the other controllers.

### To Reproduce

Steps to reproduce the behaviour:

1. Run flux bootstrap against an Openshift 4.x cluster

### Expected behavior

Bootstrapped flux-system namespace with all deployments working.

### Additional context

- Kubernetes version: 1.18.3, OpenShift 4.5.24
- Git provider: GitLab
- Container registry provider: default

Below please provide the output of the following commands:

```cli
flux --version
  flux version 0.11.0
flux check
  ► checking prerequisites
✔ kubectl 1.20.4-dirty >=1.18.0-0
✔ Kubernetes 1.18.3+fa69cae >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.10.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.11.0

kubectl -n <namespace> get all
NAME                                          READY   STATUS    RESTARTS   AGE
pod/helm-controller-7d59896db7-75h5x          1/1     Running   0          69m
pod/kustomize-controller-5946d7c748-5lnls     1/1     Running   0          69m
pod/notification-controller-cfb8b87c8-5ndzp   1/1     Running   0          69m

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/notification-controller   ClusterIP   172.30.26.78    <none>        80/TCP    69m
service/source-controller         ClusterIP   172.30.80.106   <none>        80/TCP    69m
service/webhook-receiver          ClusterIP   172.30.101.3    <none>        80/TCP    69m

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/helm-controller           1/1     1            1           69m
deployment.apps/kustomize-controller      1/1     1            1           69m
deployment.apps/notification-controller   1/1     1            1           69m
deployment.apps/source-controller         0/1     0            0           69m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/helm-controller-7d59896db7          1         1         1       69m
replicaset.apps/kustomize-controller-5946d7c748     1         1         1       69m
replicaset.apps/notification-controller-cfb8b87c8   1         1         1       69m
replicaset.apps/source-controller-546f697b96        1         0         0       69m
replicaset.apps/source-controller-64f57ffc55        0         0         0       57m


```

**Comment by hiddeco** [comment] 2021-04-06 08:47
Duplicate of #1110 #1051

**Closed by hiddeco** 2021-04-06 08:47 UTC
