### ISSUE TITLE
Use existing customised gotk-components.yaml 

### ISSUE THREAD

**Issue by Forbzy** [fluxcd/flux2#1837] opened 2021-09-18 00:04 UTC
### Describe the bug

Is there anyway during the flux bootstrap for me to use an existing gotk-components.yaml file? Mine is always over written and pushed to Github. The reason I ask is I need to be able to modify the memory and CPU resource usage of the controller components to work in my setup but it always goes back to default. 

Or is there a way to tell flux to not go to ghcr.io/fluxcd for the controller component configurations but maybe another source?

Or maybe give us a way to customise them in the same way we do with Helm values files. But I think the components would need to be a part of a helm chart to do that.

### Steps to reproduce

1. flux bootstrap github --owner=${GITHUB_USER} --repository=${GITHUB_REPO} --path=clusters/development --branch=${GITHUB_BRANCH} --read-write-key 

### Expected behavior

Flux uses configuration in existing gotk-components.yaml

### OS / Distro

Windows 10

### Flux version

0.16.0

### Flux check

► checking prerequisites
✗ flux 0.16.0 <0.17.1 (new version is available, please upgrade)
✔ kubectl 1.20.2 >=1.18.0-0
✔ Kubernetes 1.21.2 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2021-09-18 08:18
Please see the docs on how to customize the components: https://fluxcd.io/docs/installation/#customize-flux-manifests

**Comment by stefanprodan** [comment] 2021-09-18 08:20
Duplicate of https://github.com/fluxcd/flux2/discussions/1836

**Closed by stefanprodan** 2021-09-18 08:20 UTC
