### ISSUE TITLE
error: authentication required

### ISSUE THREAD

**Issue by pdev1989** [fluxcd/flux2#529] opened 2020-11-30 12:17 UTC
**Describe the bug**:
When I bootstrap flux with `--token-auth` I see "authentication required" error at the end of execution.

```
# flux bootstrap github --hostname=$GITHUB_HOSTNAME --owner=$GITHUB_USER --repository=gitops-test --branch=master --path=cluster/test --token-auth
► connecting to github.example.com
✔ repository cloned
✚ generating manifests
✔ components are up to date
► installing components in flux-system namespace
namespace/flux-system unchanged
networkpolicy.networking.k8s.io/allow-scraping unchanged
networkpolicy.networking.k8s.io/allow-webhooks unchanged
networkpolicy.networking.k8s.io/deny-ingress unchanged
role.rbac.authorization.k8s.io/crd-controller-flux-system unchanged
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system unchanged
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
service/source-controller unchanged
deployment.apps/source-controller configured
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
deployment.apps/kustomize-controller configured
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
deployment.apps/helm-controller configured
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
service/notification-controller unchanged
service/webhook-receiver unchanged
deployment.apps/notification-controller configured
deployment "source-controller" successfully rolled out
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
► applying sync manifests
◎ waiting for cluster sync
✗ unable to clone 'https://github.example.com/test/gitops-test', error: authentication required
```

My PAT that I've set in my ENV seems to be correct & has all privileges on the repo `gitops-test`. After the bootstrap execution, I can actually see `flux-system` directory created in the repo with the YAMLs files. 

```
# flux get sources git
NAME            READY   MESSAGE                                                                                                 REVISION        SUSPENDED 
flux-system     False   unable to clone 'https://github.example/test/gitops-test', error: authentication required                    False     
```

**flux check**:

```
# flux check      
► checking prerequisites
✔ kubectl 1.19.1 >=1.18.0
✔ Kubernetes 1.17.11 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.4.1
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.4.0
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.4.0
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.4.0
✔ all checks passed
```

**flux version** : 
```
#flux --version
flux version 0.4.0

```

**Comment by stefanprodan** [comment] 2020-11-30 12:34
Can you please check the content of the `flux-system` secret? The PAT should be encoded there

**Comment by pdev1989** [comment] 2020-11-30 12:39
Thanks, I checked. The decoded password is exactly the same as my PAT.

**Comment by stefanprodan** [comment] 2020-11-30 12:46
Can you also check that the secret is referenced in the `flux-system` Kustomization?

**Comment by pdev1989** [comment] 2020-11-30 13:03
I think I can't see the reference.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"10m0s","path":"./cluster/test","prune":true,"sourceRef":{"kind":"GitRepository","name":"flux-system"},"validation":"client"}}
  creationTimestamp: "2020-11-30T12:43:08Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: flux-system
  namespace: flux-system
  resourceVersion: "8293"
  selfLink: /apis/kustomize.toolkit.fluxcd.io/v1beta1/namespaces/flux-system/kustomizations/flux-system
  uid: daf5e3c6-c7fa-429f-bd6f-daa2319751d0
spec:
  interval: 10m0s
  path: ./cluster/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
status:
  conditions:
  - lastTransitionTime: "2020-11-30T12:43:08Z"
    message: Source is not ready, artifact not found
    reason: ArtifactFailed
    status: "False"
    type: Ready
  observedGeneration: 1
```

**Comment by stefanprodan** [comment] 2020-11-30 13:07
Ok can you please also post here: `kubectl -n flux-system get gitrepository flux-system -oyaml`

**Comment by pdev1989** [comment] 2020-11-30 13:12
Sure. 

```
#kubectl -n flux-system get gitrepository flux-system -oyaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta1","kind":"GitRepository","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"1m0s","ref":{"branch":"master"},"secretRef":{"name":"flux-system"},"url":"https://github.example.com/test/gitops-test"}}
  creationTimestamp: "2020-11-30T12:43:08Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: flux-system
  namespace: flux-system
  resourceVersion: "10949"
  selfLink: /apis/source.toolkit.fluxcd.io/v1beta1/namespaces/flux-system/gitrepositories/flux-system
  uid: 31517bac-36cf-4d14-ae08-b43cd1428923
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  timeout: 20s
  url: https://github.example.com/test/gitops-test
status:
  conditions:
  - lastTransitionTime: "2020-11-30T13:05:04Z"
    message: 'unable to clone ''https://github.example.com/test/gitops-test'',
      error: authentication required'
    reason: GitOperationFailed
    status: "False"
    type: Ready
  observedGeneration: 1
```

Also, I'm using GitHub Enterprise. Guess it doesn't matter here.

**Comment by stefanprodan** [comment] 2020-11-30 13:57
You need to pass `--personal` if the owner is a GH user and not a GH org.

**Comment by pdev1989** [comment] 2020-11-30 14:00
Yeah. in my case $GITHUB_USER is actually an Organization & not a user.

**Comment by stefanprodan** [comment] 2020-11-30 14:11
Hmm this is very strange, I just tested it under an GH org account and it works. What Flux version are you using?

**Comment by stefanprodan** [comment] 2020-12-01 10:20
Closing this as it proved to be a proxy related issue, duplicate of: https://github.com/fluxcd/source-controller/issues/131

**Closed by stefanprodan** 2020-12-01 10:20 UTC

**Comment by vyom-soft** [comment] 2023-03-31 21:13
> Ok can you please also post here: `kubectl -n flux-system get gitrepository flux-system -oyaml`
On GitLab, I used the following command to bootstrap. There I do not see entry for token-auth ? with the cmd you proposed.
`$flux bootstrap gitlab --owner=vyomsoft/deployment --repository=vyom-repo --path=clusters/vyom/ --token-auth --hostname=vyom.devopslab.tech`
How can I do token auth for source GitRepository?

`$flux create source git dev-monitoring --url=https://vyom.devopslab.tech/vyomsoft/deployment/vyom-repo.git --branch=main --namespace=dev-monitoring --token-auth`
There is no token auth for source git ? unknown flag: --token-auth
