### ISSUE TITLE
helm - "unable to update status after reconciliation"

### ISSUE THREAD

**Issue by iacou** [fluxcd/flux2#1070] opened 2021-03-09 09:41 UTC
### Describe the bug
Helm release status is stuck in 'reconciliation in progress', however helm controller events on the helmRelease show "Helm install succeeded", and the chart has been deployed.

These errors are present in the helm controller logs.

{"level":"error","ts":"2021-03-09T08:35:46.123Z","logger":"controller.helmrelease","msg":"unable to update status after reconciliation","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"qa-2","namespace":"qa-2","error":"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"qa-2\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":"2021-03-09T08:35:46.123Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"qa-2","namespace":"qa-2","error":"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"qa-2\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"info","ts":"2021-03-09T08:35:46.123Z","logger":"controller.helmrelease","msg":"Reconciliation is suspended for this object","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"qa-2","namespace":"qa-2"}
{"level":"info","ts":"2021-03-09T08:35:46.128Z","logger":"controller.helmrelease","msg":"Reconciliation is suspended for this object","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"qa-2","namespace":"qa-2"}

The HelmRelease has been deployed with upgrade and install retries as below:

`apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qa-2
  namespace: qa-2
spec:
  interval: 1m
  suspend: true
  chart:
    spec:
      chart: test
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: example
        namespace: flux-system
      interval: 1m
  upgrade:
    timeout: 30m
    remediation:
      retries: 3
  install:
    timeout: 30m
    remediation:
      retries: 3`

### Expected behavior

HelmRelease should not be stuck in 'reconcilition in progress' status.

### Additional context

Below please provide the output of the following commands:

```cli
► checking prerequisites
✔ kubectl 1.18.12 >=1.18.0
✔ Kubernetes 1.17.13 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.7.4
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.7.4
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.6.1
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.7.1
```

**Comment by iacou** [comment] 2021-03-09 09:43
are the retries being ignored because of the suspend: true? I am using flux in "manual" mode, deploying helmReleases with suspend: true and using the cli to flux resume - is there a workaround to allow for retries when using flux in this way?

**Comment by hiddeco** [comment] 2021-03-09 11:12
When you suspend the object, reconciliation for it stops, so anything in the `Status` object of the `HelmRelease` freezes as well.

You probably want to resume the release (by setting `suspend: false`, or removing the `suspend` declaration), and see if that magically settles things.

**Comment by iacou** [comment] 2021-03-09 11:25
OK. I'm using  "flux resume helmrelease" to trigger the release. should this not cause the suspension to be removed, or similar, to allow for the retries? Running flux resume helmrelease a second time, after the first attempt has timed out, succeeds. This is fine as a workaround (although makes the release process slow) but, is the original error message below a valid bug in itself which could be fixed to avoid needing this workaround?

"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "qa-2": the object has been modified; please apply your changes to the latest version and try again"

**Comment by iacou** [comment] 2021-03-09 11:42
yes, so as to allow us to control when a release is deployed using "flux resume helmrelease", as opposed to it getting deployed automatically as soon as it is commited to git

**Comment by hiddeco** [comment] 2021-03-09 11:46
This is what causes the issue. If you have the `suspend` field declared in Git, the `Kustomization` that synchronizes the resource to the cluster will overwrite the `suspend` field on every reconciliation `interval`.

The result of this is that when you `flux resume` the resource, it will be undone as soon as the `Kustomization` reconciles the `HelmRelease` and the object will be modified, resulting in the error you are seeing.

You should either _fully_ manage the `suspend` field through Git, or remove the field from the declaration in Git and manage it entirely using `flux suspend|resume`.

**Comment by hiddeco** [comment] 2021-04-08 08:24
Closing this as the issue is due to what I describe above, and there hasn't been any activity since.

**Closed by hiddeco** 2021-04-08 08:24 UTC
