### ISSUE TITLE
error after running  flux bootstrap 

### ISSUE THREAD

**Issue by rassidm** [fluxcd/flux2#887] opened 2021-02-08 21:01 UTC
after running  flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=fleet-infra \
  --branch=main \
  --path=./clusters/my-cluster \
  --personal
  
I get this error :

verifying installation
**notification-controller: unhealthy (timed out waiting for rollout)**
**source-controller: unhealthy (timed out waiting for rollout)**
**kustomize-controller: unhealthy (timed out waiting for rollout)**
**install failed**

I'm using Kubernetes kind
https://kind.sigs.k8s.io/

flux check --pre 
works fine 

Can uou please help 

Thank you

**Comment by hiddeco** [comment] 2021-02-10 21:50
Duplicate of https://github.com/fluxcd/flux2/discussions/886

**Closed by hiddeco** 2021-02-10 21:50 UTC
