### ISSUE TITLE
Monitoring guide is broken

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/flux2#2192] opened 2021-12-08 17:42 UTC
### Describe the bug

We're just doing an internal demo and we noticed that the Monitoring guide appears to be broken. The Flux Control Plane dashboard appears on the Grafana deployment as expected, but none of the pods match.

I have a customized version of the manifests from a fork, which could have introduced problems, but we had someone follow along with the instructions from https://fluxcd.io/docs/guides/monitoring/ and they had similar results. Metrics are not being collected from the Flux pods for some reason.

@nalum found the issue that I was experiencing was not unique to my customized version. I have one custom pod and that pod was scraped successfully for some reason. His installation had zero customized pods and zero pods were scraped.

### Steps to reproduce

Follow the monitoring guide. Notice that metrics are not being collected for the flux-system pods as expected.

### Expected behavior

Expected to see that Flux control plane was being monitored and metrics are collected. As a double-check, I deleted all the pods in the cluster and allowed them to restart. It didn't change anything.

### Screenshots and recordings

<img width="1413" alt="Screen Shot 2021-12-08 at 12 41 31 PM" src="https://user-images.githubusercontent.com/3286998/145256990-4e7e1415-2990-46d1-b98a-1c46983ae1b1.png">

### OS / Distro

MacOS 12.0.1 (Monterey)

### Flux version

v0.24.0

### Flux check

$ flux check
► checking prerequisites
✔ Kubernetes 1.21.7 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2021-12-08 17:53
Duplicate of #2150

**Comment by stefanprodan** [comment] 2021-12-08 17:54
To fix this we need to add each controller with its own key in the pod monitor.

**Comment by Nalum** [comment] 2021-12-08 17:58
I can look at picking this up if it's no one else has it on their plate

**Comment by stefanprodan** [comment] 2021-12-08 17:58
As for the Kubernetes API req duration, that's gone, we have to delete that graph see https://github.com/fluxcd/flux2/issues/1479

**Comment by stefanprodan** [comment] 2021-12-08 17:59
> I can look at picking this up if it's no one else has it on their plate

@Nalum that would be great, thank you!

**Comment by stefanprodan** [comment] 2021-12-09 08:06
Ok now that scraping is sorted, we need to delete the Kubernetes API req duration graph to close this issue.

**Closed** 2021-12-09 14:22 UTC
