### ISSUE TITLE
Helm chart to install Flux2

### ISSUE THREAD

**Issue by laszlocph** [fluxcd/flux2#537] opened 2020-12-01 14:34 UTC
I'm looking for a Helm chart to install Flux2.

Are you planning to create/maintain one, or `flux bootstrap` is the only canonical way of installing?

**Comment by stefanprodan** [comment] 2020-12-01 14:36
Duplicate of: https://github.com/fluxcd/flux2/discussions/431

**Closed by stefanprodan** 2020-12-01 14:36 UTC
