### ISSUE TITLE
manifests.embed.go:11:12: pattern manifests/*.yaml: no matching files found 

### ISSUE THREAD

**Issue by felix-hxz** [fluxcd/flux2#1188] opened 2021-03-31 09:32 UTC
manifests.embed.go:11:12: pattern manifests/*.yaml: no matching files found

**Comment by felix-hxz** [comment] 2021-03-31 09:33
This error occurred while debugging the program

**Comment by stefanprodan** [comment] 2021-03-31 09:43
Duplicate of: https://github.com/fluxcd/flux2/issues/1187 Why open a new issue when the answer is here? https://github.com/fluxcd/flux2/issues/1187#issuecomment-810914861

**Comment by hiddeco** [comment] 2021-03-31 09:47
```console
$ CGO_ENABLED=0 go build -o ./bin/flux ./cmd/flux
cmd/flux/manifests.embed.go:11:12: pattern manifests/*.yaml: no matching files found
$ make cmd/flux/manifests
./manifests/scripts/bundle.sh
[INFO]  using {4.0.1  2021-02-21T13:20:22Z  }
[INFO]  building helm-controller.yaml
[INFO]  building image-automation-controller.yaml
[INFO]  building image-reflector-controller.yaml
[INFO]  building kustomize-controller.yaml
[INFO]  building notification-controller.yaml
[INFO]  building source-controller.yaml
[INFO]  building rbac.yaml
[INFO]  building policies.yaml
$ make build
CGO_ENABLED=0 go build -o ./bin/flux ./cmd/flux
```

**Closed by hiddeco** 2021-03-31 09:47 UTC
