### ISSUE TITLE
Manifests not generated when bootstrap on windows 10

### ISSUE THREAD

**Issue by xiemeilong** [fluxcd/flux2#574] opened 2020-12-10 05:45 UTC
```
flux bootstrap gitlab --repository gitops --hostname code.xxxx.com --branch master --owner devops --path iot
► connecting to code.xxxx.com
✔ repository cloned
✚ generating manifests
✗ generating install manifests failed: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\Administrator\AppData\Local\Temp\kustomize-937822732\repo'
```

the kustomize-937822732 folder not exists.

**Comment by stefanprodan** [comment] 2020-12-10 07:50
Duplicate of: #362

**Closed by stefanprodan** 2020-12-10 07:50 UTC
