### ISSUE TITLE
image updates policy moves comments and alters indentation

### ISSUE THREAD

**Issue by fragolinux** [fluxcd/flux2#1441] opened 2021-05-21 15:55 UTC
### Describe the bug

applying image update automation reformats yaml moving around comments (altering given order), and indents yaml sections back of 2 spaces

### To Reproduce

Steps to reproduce the behaviour:

for comments:
original yaml block:
```
  values:
    # storage:
    #   multiWriteStorageClass: nfs

    ingress:
      host: lab
      extra:
        annotations:
          alb.ingress.kubernetes.io/tags: Env=LabQA
      annotations:
        certificate:
          arn: arn:aws:acm:eu-central-1:..........................
```
altered block:
```
  values:
    ingress:
      host: lab
      extra:
        annotations:
          alb.ingress.kubernetes.io/tags: Env=LabQA
      annotations:
        certificate:
          arn: arn:aws:acm:eu-central-1:..........................
    # storage:
    #   multiWriteStorageClass: nfs
```

for indentation:
original yaml block:
```
        database:
          connections:
            - name: readonlyRegular
              connectTimeoutMS: 60000
              socketTimeoutMS: 600000
```
altered block:
```
        database:
          connections:
          - name: readonlyRegular
            connectTimeoutMS: 60000
            socketTimeoutMS: 600000
```

### Expected behavior

keep comments and indentation in the way it is in original files, altering just the image updates tagged lines...

**Comment by stefanprodan** [comment] 2021-05-24 11:09
Duplicate of: https://github.com/fluxcd/image-automation-controller/issues/117
Upstream bug: https://github.com/kubernetes-sigs/kustomize/issues/3559

**Closed by stefanprodan** 2021-05-24 11:09 UTC
