### ISSUE TITLE
Kustomize helm chart

### ISSUE THREAD

**Issue by raffis** [fluxcd/flux2#575] opened 2020-12-10 08:08 UTC
How can I apply a kustomization patch to a helm chart? If this is already possible it's quite hidden in the docs 😎 .
Basically I want to template a helm chart from a `HelmRepository` apply kustomize and apply the manifests to the cluster, not actually install the chart. (That would be nice as well, template the chart, apply patches, bump chart version, package and install).

**Comment by stefanprodan** [comment] 2020-12-10 08:12
You can do it in CI, run `helm template` and push the manifests to a branch where your kustomization.yaml is. Then with a GitRepository and Kustomization apply the kustomize overlay on the cluster.

**Comment by raffis** [comment] 2020-12-10 08:17
Yeah something like that would be the way to go. However this would be really nice to have as a feature. 
Basically I want to patch a 3rd party helm chart which does not offer all the flexibility I need which is quite a common use case for kustomize.

**Comment by stefanprodan** [comment] 2020-12-10 08:23
Duplicate of: https://github.com/fluxcd/helm-controller/issues/104

**Closed by stefanprodan** 2020-12-10 08:23 UTC
