### ISSUE TITLE
  In-order cleanup is required for tools like rook 

### ISSUE THREAD

**Issue by telmich** [fluxcd/flux2#1614] opened 2021-07-11 14:46 UTC
**Describe the bug**

If changing the rook resources (see https://code.ungleich.ch/ungleich-public/ungleich-k8s/-/tree/master/rook for a condensed example), it must be deleted and created in order, see https://rook.io/docs/rook/v1.6/ceph-teardown.html

If not deleted in order, the namespace will never be freed.

**To Reproduce**

Install above set of manifests via flux, modify it so that flux recreates it - for instance by rename the kustomization. 

**Expected behavior**

Flux needs to have a way to delete in order.

**Additional context**

- Flux version: 0.16
- Kubernetes version: 1.21.2
- Git provider: any
- Container registry provider: any

**Comment by hiddeco** [comment] 2021-07-12 07:26
Duplicate of https://github.com/fluxcd/kustomize-controller/issues/301

**Closed by hiddeco** 2021-07-12 07:26 UTC
