### ISSUE TITLE
Flux stuck on apply simultaneously operator that create crd and it's crd.

### ISSUE THREAD

**Issue by xriser** [fluxcd/flux2#1482] opened 2021-06-06 09:22 UTC
I have a repository with Postgres operator deployment manifest in one yaml file, and configuration for it (kind: "postgresql") in another file.
When flux applying changes it does sort manifests by kinds and applying them

https://github.com/fluxcd/flux/blob/master/pkg/cluster/kubernetes/sync.go#L494-L513

The issue, flux trying to apply configuration for postgres and fails because the CRD doesn't exist at the moment.
However, flux stucking and do not apply other manifests from the repo.
```
{"level":"error","ts":"2021-06-06T09:03:15.423Z","logger":"controller.kustomization","msg":"Reconciliation failed after 2.612033703s, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"main/8162c89c26d5cc3fe080777aa631341212094fe4","error":"validation failed: error: unable to recognize \"dabd334f-f622-46ac-b8ff-d5934bddcf39.yaml\": no matches for kind \"postgresql\" in version \"acid.zalan.do/v1\"\n"}
{"level":"error","ts":"2021-06-06T09:13:18.077Z","logger":"controller.kustomization","msg":"Reconciliation failed after 2.648682495s, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"main/8162c89c26d5cc3fe080777aa631341212094fe4","error":"validation failed: error: unable to recognize \"dabd334f-f622-46ac-b8ff-d5934bddcf39.yaml\": no matches for kind \"postgresql\" in version \"acid.zalan.do/v1\"\n"}

```
The same behavior if there is an error in some manifest. 
Is there some option to skip "failed" manifests and continue applying others?

To add more context here: If flux skip "failed" manifests because there is no CRD at the moment, and apply other manifests(postrgres operator manifest will create CRD), and then on the next try "failed" manifests will be valid, and applied successfully.

- Kubernetes version: 1.20
- Git provider: github
- Container registry provider: docker

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.13.4
flux check
► checking prerequisites
✗ flux 0.13.4 <0.14.2 (new version is available, please upgrade)
✔ kubectl 1.21.0 >=1.18.0-0
✔ Kubernetes 1.20.6-gke.1000 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.9.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.9.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.2
✔ all checks passed


kubectl -n <namespace> logs deploy/kustomize-controller

{"level":"error","ts":"2021-06-06T09:13:18.077Z","logger":"controller.kustomization","msg":"Reconciliation failed after 2.648682495s, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"main/8162c89c26d5cc3fe080777aa631341212094fe4","error":"validation failed: error: unable to recognize \"dabd334f-f622-46ac-b8ff-d5934bddcf39.yaml\": no matches for kind \"postgresql\" in version \"acid.zalan.do/v1\"\n"}

```

**Comment by alllexandrz** [comment] 2021-06-06 09:26
Hey Team.
I have the same issue. 
Can you implement some kind of dependency or sorting?

**Comment by stefanprodan** [comment] 2021-06-06 10:44
Read the docs please: https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies

**Comment by xriser** [comment] 2021-06-06 13:01
Thank you @stefanprodan, this will help with depend on deployments, but what about "flux stuck and stops applying manifests if already error"
I had many cases when the error in one manifest in repo prevent flux from applying other ones.

**Comment by stefanprodan** [comment] 2021-06-06 17:37
@xriser that’s by design, otherwise Flux would bring the cluster into a state that no longer matches a commit. You can disable this behavior by setting `validation: none` in the Flux Kustomization, but I strongly advise against it. See this example on how to validate your manifests before they get merged and synced: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh

**Closed** 2021-06-25 09:40 UTC
