### ISSUE TITLE
Kustomize error after cluster rebuild

### ISSUE THREAD

**Issue by BobWieberdink** [fluxcd/flux2#2436] opened 2022-02-14 15:40 UTC
### Describe the bug

	Flux Bootstrap fails when running in rebuilt cluster. After having rebuilt cluster with a running instance of Flux2 
	we are seeing errors when running the bootstrap routine on the newly rebuilt cluster:
	► connecting to github.com
	✔ repository "https://github.com/<redacted>/<redacted>" reconciled
	► cloning branch "<redacted>" from Git repository "https://github.com/<redacted>/<redacted>"
	✔ cloned repository
	► generating component manifests
	✔ generated component manifests
	✔ component manifests are up to date
	► installing components in "flux" namespace
	✗ Kustomization/flux/flux dry-run failed, error: no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"

If we install the CRDs before running the bootstrap routine on the rebuilt cluster it completes successfully.

### Steps to reproduce

	Bootstrap Flux on new/running Kubernetes cluster creating new flux manifests in repo.
	Delete/rebuild Kubernetes cluster. Flux manifests in remain in repo.
	Run Bootstrap routine on rebuilt cluster.
	Error occurs:
	► connecting to github.com
	✔ repository "https://github.com/<redacted>/<redacted>" reconciled
	► cloning branch "<redacted>" from Git repository "https://github.com/<redacted>/<redacted>"
	✔ cloned repository
	► generating component manifests
	✔ generated component manifests
	✔ component manifests are up to date
	► installing components in "flux" namespace
	✗ Kustomization/flux/flux dry-run failed, error: no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
	
	We recreate the CRDs before running the bootstrap on the rebuilt cluster:
	kubectl apply -f ./flux_crd.yaml -n flux (flux_crd.yaml created from gotk-components.yaml in flux manifests and only contains CRDs)
	customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/imagepolicies.image.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/imagerepositories.image.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/imageupdateautomations.image.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io created
	customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io created
	
	Run bootstrap again on rebuilt cluster and it completes successfully:
	► connecting to github.com
	✔ repository "https://github.com/<redacted>/<redacted>"reconciled
	► cloning branch "<redacted>" from Git repository "https://github.com/<redacted>/<redacted>"
	✔ cloned repository
	► generating component manifests
	✔ generated component manifests
	✔ component manifests are up to date
	► installing components in "flux" namespace
	✔ installed components
	✔ reconciled components
	► determining if source secret "<redacted>" exists
	✔ source secret up to date
	► generating sync manifests
	✔ generated sync manifests
	✔ sync manifests are up to date
	applying sync manifests
	✔ reconciled sync configuration
	◎ waiting for Kustomization "flux/flux" to be reconciled
	✔ Kustomization reconciled successfully
	► confirming components are healthy
	✔ helm-controller: deployment ready
	✔ image-automation-controller: deployment ready
	✔ image-reflector-controller: deployment ready
	✔ kustomize-controller: deployment ready
	✔ notification-controller: deployment ready
	✔ source-controller: deployment ready
	✔ all components are healthy
	
	If flux manifests are deleted in the repo when the cluster is deleted/rebuilt, bootstrap routine runs successfully.

### Expected behavior

	Bootstrap routine creates CRDs from flux manifests in repo if flux manifests exist in the repo and if CRDs don't currently
	exist in the cluster before attempting to reinstall flux components on the rebuilt cluster

### Screenshots and recordings

N/A

### OS / Distro

Amazon Linux 2.0

### Flux version

0.25.3

### Flux check

► checking prerequisites
✗ flux 0.25.3 <0.26.3 (new version is available, please upgrade)
✔ Kubernetes 1.20.11-eks-f17b81 >=1.19.0-0
► checking controllers
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2022-02-14 15:41
Duplicate of: https://github.com/fluxcd/flux2/issues/2351

PS. This bug was fixed in 0.26.3

**Closed by stefanprodan** 2022-02-14 15:41 UTC
