### ISSUE TITLE
Add render helmrelease for flux

### ISSUE THREAD

**Issue by mv-yurchenko** [fluxcd/flux2#4124] opened 2023-08-02 08:59 UTC
Debugging configuration examples would benefit with a new render subcommand to flux whereby the fully rendered manifests defined by a HelmRelease object are output. You'd run

`flux render helmrelease my-release`

and get the streamed manifests as they were (our would have been except for an error) applied to K8S.

**Comment by stefanprodan** [comment] 2023-08-02 14:44
Duplicate of: https://github.com/fluxcd/flux2/issues/2808

**Closed by stefanprodan** 2023-08-02 14:44 UTC
