### ISSUE TITLE
Bootstrap creates empty files

### ISSUE THREAD

**Issue by Marx2** [fluxcd/flux2#583] opened 2020-12-11 11:13 UTC
Bootstrap command doesn't want to install on existing GIT repository. I can live with it, so I've decided to allow it create new repository. Here's a log of creation:
```
 $ flux bootstrap github   --token-auth   --hostname=github.tools.xxx   --owner=yyyy   --repository=kubernetes-config2   --branch=master   --path=/clusters/k3sdev   --team=zzzz
► connecting to github.tools.xxx
✔ repository created
✔ zzzz team access granted
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system created
networkpolicy.networking.k8s.io/allow-scraping created
networkpolicy.networking.k8s.io/allow-webhooks created
networkpolicy.networking.k8s.io/deny-ingress created
role.rbac.authorization.k8s.io/crd-controller-flux-system created
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io created
service/source-controller created
deployment.apps/source-controller created
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io created
deployment.apps/kustomize-controller created
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io created
deployment.apps/helm-controller created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io created
service/notification-controller created
service/webhook-receiver created
deployment.apps/notification-controller created
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "source-controller" successfully rolled out
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
Waiting for deployment "notification-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✗ kustomization path not found: stat /tmp/flux-system309109433/clusters/k3sdev: no such file or directory
```
Repository has been created, README.md is created, but yaml files are empty. Should they?
Listing logs repository shows:
```
$ git log -p
commit cf5e74b0428674aced9f2fd1b45f7d147991fb40 (HEAD -> master, origin/master, origin/HEAD)
Author: flux <xxxx>
Date:   Fri Dec 11 10:58:55 2020 +0100

    Add manifests

commit bea83df32c89baeec8031da2235b83504a43c6c3
Author: flux <xxxx>
Date:   Fri Dec 11 10:58:35 2020 +0100

    Add manifests

commit 0bd99a15329e3370dcf82833455e82efb8ff35d7
Author: xxxx <xxxx>
Date:   Fri Dec 11 10:58:31 2020 +0100

    Initial commit
```

**Comment by stefanprodan** [comment] 2020-12-11 11:57
Can you post here `flux -v` and say what OS are you using to run the CLI please?

**Comment by Marx2** [comment] 2020-12-11 12:15
```
 $ flux -v
flux version 0.4.3
```
Latest version from brew.
It's Catalina Mac OS.
I've just noticed, that those yamls are not emty files, but folders (?)
![image](https://user-images.githubusercontent.com/822886/101902422-e78e1d00-3bb2-11eb-9e2c-4435deed295e.png)

**Comment by stefanprodan** [comment] 2020-12-11 12:18
Hmm something is very wrong... I can't reproduce this on Catalina 10.15.7 nor on Linux, you could run it inside a container or VM.

**Comment by Marx2** [comment] 2020-12-11 12:23
Can it be something with GIT(hub) configuration? I use company's Enterprise Github. Have you tried not "--personal" repository? Is it possible to tell flux to leave manifests in this temporary folder? I can commit them myself. Or can I copy/generate them from another place and put manually into GIT?

**Comment by stefanprodan** [comment] 2020-12-11 12:26
For manual bootstrap please see the docs: https://toolkit.fluxcd.io/guides/installation/#generic-git-server

**Comment by Marx2** [comment] 2020-12-11 13:43
I repeated installation on Linux VM with exactly the same result. The I've tried to interrupt on the step "► generating sync manifests". Folder /tmp/flux-system690061622 looks ok, contains 3 files:
<img width="165" alt="image" src="https://user-images.githubusercontent.com/822886/101910139-d3501d00-3bbe-11eb-924b-034aeacd6ff7.png">
Looking at git repo locally it looks like this:
```
/tmp/flux-system690061622$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   /clusters/k3sdev/flux-system/gotk-components.yaml
	new file:   /clusters/k3sdev/flux-system/gotk-sync.yaml
	new file:   /clusters/k3sdev/flux-system/kustomization.yaml

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    /clusters/k3sdev/flux-system/gotk-components.yaml
	deleted:    /clusters/k3sdev/flux-system/gotk-sync.yaml
	deleted:    /clusters/k3sdev/flux-system/kustomization.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	clusters/
```

**Comment by stefanprodan** [comment] 2020-12-11 13:46
> I repeated installation on Linux VM with exactly the same result.

Have you used a new repository?

**Comment by Marx2** [comment] 2020-12-11 13:47
yes, everytime I delete this repo and let it recreate everything

**Comment by stefanprodan** [comment] 2020-12-11 14:09
Maybe this is related to your Github Enterprise, we run e2e tests for bootstrap on github.com and I've also tested again with a GitHub org, no luck on reproducing this.

**Comment by Marx2** [comment] 2020-12-11 14:48
I understand it's really weird
I've added those files with intention to commit and see what happened.Take especially a look at  /clusters... and  clusters... It looks like staging files to GIT were done somehow with absolute path, while it should be with local paths. I supoose there's some code which works differently for Github Enterprise, maybe it concatenate/build GIT commands in different way

```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   /clusters/k3sdev/flux-system/gotk-components.yaml
	new file:   /clusters/k3sdev/flux-system/gotk-sync.yaml
	new file:   /clusters/k3sdev/flux-system/kustomization.yaml
	new file:   clusters/k3sdev/flux-system/gotk-components.yaml
	new file:   clusters/k3sdev/flux-system/gotk-sync.yaml
	new file:   clusters/k3sdev/flux-system/kustomization.yaml

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    /clusters/k3sdev/flux-system/gotk-components.yaml
	deleted:    /clusters/k3sdev/flux-system/gotk-sync.yaml
	deleted:    /clusters/k3sdev/flux-system/kustomization.yaml
```

**Comment by Marx2** [comment] 2020-12-11 14:57
Applying manually yamls is not fully successful:
`error: unable to recognize "kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"`

**Comment by stefanprodan** [comment] 2020-12-11 15:02
You need to apply with `kubectl apply -k`

**Comment by hiddeco** [comment] 2020-12-11 15:08
Given we made changes to how we work with paths in `v0.5.0`, it may be worth checking out if the issue is magically resolved in the release that just came out :sparkles:

**Comment by Marx2** [comment] 2020-12-11 17:02
I've repeated whole process forcing 0.5.0 like this:
flux bootstrap github \
  --token-auth \
  --hostname=${GITHUB_HOST} \
  --owner=${GITHUB_ORG} \
  --repository=${GITHUB_REPO} \
  --branch=master \
  --path=/clusters/k3sdev \
  --team=some-team \
  --version=0.5.0 \
  --verbose
It installed:
- ghcr.io/fluxcd/helm-controller:v0.4.3
- ghcr.io/fluxcd/kustomize-controller:v0.5.0
- ghcr.io/fluxcd/notification-controller:v0.5.0
- ghcr.io/fluxcd/source-controller:v0.5.2
It doesn't seem to install the newest version, for example source controller is available 0.5.3
Anyway, output is exactly the same: folders in GIT instead of files.

**Comment by hiddeco** [comment] 2020-12-11 17:20
There isn't any more debug output, as [our process of working with Git is very simple and does not rely on `git`](https://github.com/fluxcd/pkg/blob/main/git/repository.go#L122). As you mention that the creation of the files in `/tmp` works fine, the area to look at is very small:

https://github.com/fluxcd/flux2/blob/main/cmd/flux/bootstrap_github.go#L261-L274

**Comment by Marx2** [comment] 2020-12-11 17:40
I'm not sure.
I've tried again:
```
Waiting for deployment "notification-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "notification-controller" successfully rolled out
✔ install completed
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
```
then I've interrupted process, as the next message is last message with failing to find "kustomization path", and then temp folder is deleted.
Files are there, but they have different attributes:
```
-rwxr-xr-x 1 hybris hybris 113649 Dec 11 18:34 gotk-components.yaml
-rwxr-xr-x 1 hybris hybris    551 Dec 11 18:34 gotk-sync.yaml
-rw-r--r-- 1 hybris hybris    115 Dec 11 18:34 kustomization.yaml
```
But in repo I have folders instead of files (?).
And local GIT repo is not clean.

**Comment by hiddeco** [comment] 2020-12-11 18:06
When you tried it on `v0.5.x`, did you truncate the repository or used an existing one?

**Comment by Marx2** [comment] 2020-12-11 18:26
I always completely delete repository and let flux recreate it from scratch

**Comment by Marx2** [comment] 2020-12-13 13:36
I've repeated whole process using personal GitHub account. The outcome is the same.
This is repository which has been created:
https://github.com/Marx2/kubernetes-config/tree/main/clusters/k3sdev
Log:
```
 flux bootstrap github   --owner=${GITHUB_USER}   --repository=${GITHUB_REPO}   --branch=main   --path=/clusters/k3sdev   --personal
► connecting to github.com
✔ repository created
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
namespace/flux-system created
networkpolicy.networking.k8s.io/allow-scraping created
networkpolicy.networking.k8s.io/allow-webhooks created
networkpolicy.networking.k8s.io/deny-ingress created
role.rbac.authorization.k8s.io/crd-controller-flux-system created
rolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io created
service/source-controller created
deployment.apps/source-controller created
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io created
deployment.apps/kustomize-controller created
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io created
deployment.apps/helm-controller created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io created
service/notification-controller created
service/webhook-receiver created
deployment.apps/notification-controller created
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "source-controller" successfully rolled out
Waiting for deployment "kustomize-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► configuring deploy key
✔ deploy key configured
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✗ kustomization path not found: stat /tmp/flux-system261918177/clusters/k3sdev: no such file or directory
```
Exports before command has been issued:
```
export GITHUB_TOKEN=<mytoken>
export GITHUB_REPO=kubernetes-config
export GITHUB_USER=Marx2
```

Any idea what I'm doing wrong?

**Comment by Marx2** [comment] 2020-12-14 06:45
I've tried with newest version
```
flux -v
flux version 0.5.4
```
Still the same result.

**Comment by hiddeco** [comment] 2020-12-14 09:11
I was able to reproduce your issue by using `--path=/foo/bar`. If you provide a relative path (`--path=foo/bar` or `--path=./foo/bar`), I expect it to work.

Am writing a validation rule as we speak to prevent other people from running into this.

**Closed** 2020-12-14 14:23 UTC
Labels: area/bootstrap, bug
