### ISSUE TITLE
Flux bootstrap failed to generate component manifests

### ISSUE THREAD

**Issue by tylerforaie** [fluxcd/flux2#2020] opened 2021-10-28 02:42 UTC
### Describe the bug

The flux bootstrap command failed while generating the manifests and threw the following error

`component manifest generation failed: Rel: can't make C:\Users\Tyler\AppData\Local\Temp\flux-manifests-1889500201 relative to F:\Work\k8s.development`

The error was throw from [line139](https://github.com/fluxcd/flux2/blob/0e747790f920f5d873784ddc07cbcb768d5f2873/internal/bootstrap/bootstrap_plain_git.go#L139) of the `bootstrap_plain_git.go` file

[SecureJoin ](https://github.com/fluxcd/flux2/blob/0e747790f920f5d873784ddc07cbcb768d5f2873/pkg/manifestgen/install/install.go#L39) is what seems to have throw the error

I was able to successfully run the bootstrap command by setting my terminal path to the C drive and running the command again

### Steps to reproduce

1. Have your terminal location set to a Drive other than the C drive
2. Run flux bootstrap

### Expected behavior

The manifests to be generated and the bootstrap command to be successful

### OS / Distro

Windows 10 Pro Build 19042.1288

### Flux version

0.19.0

### Flux check

N/A

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2021-11-03 08:47
Duplicate of: #1153

**Closed by stefanprodan** 2021-11-03 08:47 UTC
Labels: area/bootstrap
