### ISSUE TITLE
Support for use of webproxy

### ISSUE THREAD

**Issue by andloh** [fluxcd/flux2#946] opened 2021-02-18 22:34 UTC
### Describe the bug

This is more of a feature request. Add support to reach the internet (github) through a webproxy.
This is probably already works with the use of HTTP/S_PROXY envvars, but only if you are using PAT for authentication, not for deployment keys.

If your gonna use deployment keys behind a proxy, ssh needs to know how to tunnel the connection. With the use of `socat` and `proxycommand` for your ~/.ssh/config, this can be achieved with the following: 

```bash
host github.com
    hostname ssh.github.com
    port 443
    proxycommand socat - PROXY:your.proxy.ip:%h:%p,proxyport=3128,proxyauth=user:pwd
```
To do this today with flux2, we have to create our own custom image with socat installed and this config as a configmap + config in the targeted deployment to map the config. This makes it hard to manage and upgrade flux2

### Expected behavior

A flag in the installation process to specify your proxy-needs and `socat` or another similar tool to handle SOCKS in the targeted containers

Below please provide the output of the following commands:

```cli
flux --version flux version 0.8.1
```

**Comment by stefanprodan** [comment] 2021-02-19 08:11
Duplicate of: https://github.com/fluxcd/source-controller/issues/131

**Closed by stefanprodan** 2021-02-19 08:11 UTC
