### ISSUE TITLE
Helm chart latest version not picked up

### ISSUE THREAD

**Issue by mariusrugan** [fluxcd/flux2#2185] opened 2021-12-07 10:31 UTC
### Describe the bug

hi,

Flux helm-controller cannot find & pull Traefik latest chart and pulls 2 versions ago if left to decide.
Please advise, thanks!

### Steps to reproduce

using as per below HelmRelease,HelmRepository combo,
flux 0.24.0,

```
flux: v0.24.0
helm-controller: v0.14.0
kustomize-controller: v0.18.1
notification-controller: v0.19.0
source-controller: v0.19.0
```

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.7.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 10m
``` 
with

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
  timeout: 3m
```

cannot find latest chart, although helm CLI can,

```
chart pull error: failed to get chart version for remote reference: no 'traefik' chart with version matching '10.7.1' found
```

```
helm show all traefik/traefik | more
```

```
apiVersion: v2
appVersion: 2.5.4
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ldez@traefik.io
  name: ldez
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 10.7.1
```

if version is omitted in HelmRelease to leave it up to flux, pull 2 versions ago, 10.6.2
```
NAME   	READY	MESSAGE                         	REVISION	SUSPENDED
traefik	True 	Release reconciliation succeeded	10.6.2  	False
```

### Expected behavior

Flux should pull latest specified in index.yaml

### OS / Distro

MacOS 

### Flux version

v0.24.0

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.21.5-gke.1302 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.0
✔ all checks passed


### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment] 2021-12-10 09:17
I wasn't able to reproduce the error you're seeing locally. Would you mind posting the output of the following command here, please?
```
kubectl get helmrepo -n flux-system traefik-charts -o yaml
```

**Comment by hiddeco** [comment] 2021-12-10 09:44
Based on the `24h` interval in your `HelmRepository` resource, I am wondering if the `index.yaml` as cached by the source-controller, which is used to determine the latest version of the `HelmChart`, simply wasn't up-to-date yet with the latest releases.

Which would explain it not "seeing" the version you are seeing locally, with an up-to-date index :-).

**Comment by makkes** [comment] 2021-12-10 10:38
> Based on the `24h` interval in your `HelmRepository` resource, I am wondering if the `index.yaml` as cached by the source-controller, which is used to determine the latest version of the `HelmChart`, simply wasn't up-to-date yet with the latest releases.
> 
> Which would explain it not "seeing" the version you are seeing locally, with an up-to-date index :-).

Right, 10.7.1 has been published in the afternoon of Dec 6 and this issue has been opened less than 24h after that. Good catch.

@mariusrugan can you check if the issue is still apparent?

**Comment by mariusrugan** [comment] 2021-12-10 11:18
hi,

thanks for looking into this, indeed, 
i've lowered the interval to 1h and updated the HelmRelease/Repo, sorry for that, _before_ i saw your request for helmrepo dump; 
the updated one is picking up the latest, 10.7.1, so indeed it was a cache issue ? 

I'm also looking at the index.yaml and see the [https://helm.traefik.io/traefik/index.yaml]
```
created: "2021-12-06T16:36:37.353217757Z"
```
is the same for all entries, - dunno if indexing bit of the code parses that and is confused because everything is in the same timestamp roughly; 
also what i observed was 2 versions 10.7.1, 10.7.0 were not found when requested.
However - now works - as intended will keep an eye on this and thanks for pointing out debugging the HelmRepo - probably i should be looking at lastUpdateTime ?

thanks again!
```
kubectl get helmrepo -n flux-system traefik-charts -o yaml

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  creationTimestamp: "2021-12-06T11:23:37Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 4
  labels:
    kustomize.toolkit.fluxcd.io/name: environments
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: traefik-charts
  namespace: flux-system
  resourceVersion: "4681165"
  uid: 3337caed-bc02-4a63-bb42-1cba65d94bc7
spec:
  interval: 1h
  timeout: 3m
  url: https://helm.traefik.io/traefik
status:
  artifact:
    checksum: 95ea97f19041c86fad7cb28b0c8c76d59f31b908a19970562613939c99b60f8b
    lastUpdateTime: "2021-12-10T11:03:49Z"
    path: helmrepository/flux-system/traefik-charts/index-95ea97f19041c86fad7cb28b0c8c76d59f31b908a19970562613939c99b60f8b.yaml
    revision: 95ea97f19041c86fad7cb28b0c8c76d59f31b908a19970562613939c99b60f8b
    url: http://source-controller.flux-system.svc.cluster.local./helmrepository/flux-system/traefik-charts/index-95ea97f19041c86fad7cb28b0c8c76d59f31b908a19970562613939c99b60f8b.yaml
  conditions:
  - lastTransitionTime: "2021-12-10T11:03:49Z"
    message: 'Fetched revision: 95ea97f19041c86fad7cb28b0c8c76d59f31b908a19970562613939c99b60f8b'
    reason: IndexationSucceed
    status: "True"
    type: Ready
  observedGeneration: 4
  url: http://source-controller.flux-system.svc.cluster.local./helmrepository/flux-system/traefik-charts/index.yaml
```

**Comment by makkes** [comment] 2021-12-10 11:57
@mariusrugan happy you got this resolved. Feel free to close this issue.

**Closed** 2021-12-10 14:32 UTC
Labels: area/helm
