### ISSUE TITLE
Flux cannot reconcile to nothing

### ISSUE THREAD

**Issue by Poundex** [fluxcd/flux2#1192] opened 2021-04-01 10:34 UTC
kustomize-controller: v0.10.0

Flux fails to reconcile when the target is nothing.

We were testing our Flux set up and had two deployments in a repository which is watched by a GitRepository. We deleted one of them and Flux reconciled successfully and removed this deployment's resources as expected. When the second deployment was removed no resources were deleted and we started seeing errors.

kustomize-controller says:
> {
  "level": "error",
  "ts": "2021-04-01T10:04:35.895Z",
  "logger": "controller.kustomization",
  "msg": "Reconciliation failed after 190.173565ms, next try in 10m0s",
  "reconciler group": "kustomize.toolkit.fluxcd.io",
  "reconciler kind": "Kustomization",
  "name": "flux-system",
  "namespace": "flux-system",
  "revision": "master/526b0335c05cb47571fbe2df3e8ed0e8e9a4a06d",
  "error": "validation failed: error: no objects passed to apply\n"
}

Trying to reconcile this manually using the CLI:
> $ flux --verbose reconcile kustomization flux-system                       
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✔ Kustomization reconciliation completed
✗ Kustomization reconciliation failed

We were able to work around this issue by adding an empty no-op ConfigMap to the GitRepository. When this was applied flux then deleted the previously removed deployment as expected, so it seems flux always needs at least one manifest to apply.

Use-case for nothing: one of the clusters that will be running Flux will be for bespoke client demos. It is conceivable that there will be times with no active demo deployments.

**Comment by stefanprodan** [comment] 2021-04-02 06:20
Duplicate of: https://github.com/fluxcd/kustomize-controller/issues/187

**Closed by stefanprodan** 2021-04-02 06:20 UTC
