### ISSUE TITLE
How to use specific gates for approving the deployment before going to preprod and prod , please share any sample

### ISSUE THREAD

**Issue by zameer712** [fluxcd/flux2#4637] opened 2024-02-29 07:16 UTC
### Describe the bug

Hello Team,

Do we have any example of how to apply gates on specific deployments to avoid its continuous roll out till production

please let me know

Regards
Roshan

### OS / Distro

Linux

### Flux version

v0.20.1

### Flux check

all are working are fine

### Git provider

github

### Additional context

Hello Team,

Do we have any example of how to apply gates on specific deployments to avoid its continuous roll out till production

please let me know

Regards
Roshan

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wilmardo** [comment] 2024-03-26 12:53
There has been some talk about this but it currently isn't possible, see this issue:
https://github.com/fluxcd/flux2/issues/3164

**Comment by stefanprodan** [comment] 2024-04-04 07:42
Duplicate of: https://github.com/fluxcd/flux2/issues/3164

**Closed by stefanprodan** 2024-04-04 07:42 UTC
