### ISSUE TITLE
flux.sh always installs the latest version

### ISSUE THREAD

**Issue by iyermako** [fluxcd/flux2#2590] opened 2022-03-29 07:33 UTC
### Describe the bug

Looks like install script doesn't respect a specified flux version and always download the latest. 

### Steps to reproduce

Any thing like 
export FLUX_VERSION=0.25.3
curl -s https://raw.githubusercontent.com/fluxcd/flux2/v0.25.3/install/flux.sh | sudo bash
seem not working as expected

### Expected behavior

The script installs a specified version of the tool.

### OS / Distro

macOS 12.03, CentOS 7

### Flux version

N/A

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.3 >=1.20.6-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2022-03-29 08:15
Duplicate of: https://github.com/fluxcd/flux2/discussions/2396

**Closed** 2022-03-29 09:02 UTC
Labels: duplicate
