### ISSUE TITLE
Deleted kustomization and helmrelease still show up in `flux get ...`

### ISSUE THREAD

**Issue by beyondbill** [fluxcd/flux2#1019] opened 2021-03-01 22:43 UTC
I've been seeing a lingering kustomization and helmrelease that have been deleted both from git source and flux CLI. Is it a bug?

```
➜  ~ flux delete kustomization dev-team -n ufl-storage --verbose                                                                                                                                
Are you sure you want to delete this kustomizations: y
► deleting kustomizations dev-team in ufl-storage namespace
✔ kustomizations deleted
➜  ~ flux get kustomization -A                                                                                                                                                                  
NAMESPACE  	NAME          	READY	MESSAGE                                                                                                            	REVISION                                     	SUSPENDED
apps       	dev-team      	True 	Applied revision: main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36                                                    	main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36	False
flux-system	flux-system   	True 	Applied revision: main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36                                                    	main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36	False
flux-system	infrastructure	True 	Applied revision: main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36                                                    	main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36	False
flux-system	tenants       	True 	Applied revision: main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36                                                    	main/b01ad76cbe9b1ee2ac8dccfa69821c54698aab36	False
ufl-storage	dev-team      	False	kustomization path not found: stat /tmp/dev-team395255135/dev-team/test-flux/ufl-storage: no such file or directory	main/ba3f35f1661576f1c912db5068ed88f8219d7aab	False
```

```
➜  ~ flux delete helmrelease ufl-storage -n ufl-storage --verbose                                                                                                                                                  
Are you sure you want to delete this helmreleases: y
► deleting helmreleases ufl-storage in ufl-storage namespace
✔ helmreleases deleted
➜  ~ flux get helmrelease -n ufl-storage                                                                                                                                                                           
NAME       	READY	MESSAGE                                                                             	REVISION	SUSPENDED
ufl-storage	False	could not impersonate ServiceAccount 'dev-team': ServiceAccount "dev-team" not found	        	False
```

### Additional context

```
➜  ~ flux --version                                                                                                                                                                                                (gke_dulcet-yew-246109_us-west1_donkey-us-west1/default)

flux version 0.8.2
➜  ~ flux check                                                                                                                                                                                                    (gke_dulcet-yew-246109_us-west1_donkey-us-west1/default)

► checking prerequisites
✗ flux 0.8.2 <0.9.0 (new version is available, please upgrade)
✔ kubectl 1.20.2 >=1.18.0-0
✔ Kubernetes 1.16.15-gke.11800 >=1.16.0-0
► checking controllers
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.7.0
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.8.1
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.8.0
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.8.1
✔ all checks passed
```

**Comment by stefanprodan** [comment] 2021-03-02 05:46
Duplicate of: https://github.com/fluxcd/flux2/issues/997

**Closed by stefanprodan** 2021-03-02 05:46 UTC

**Comment by beyondbill** [comment] 2021-03-02 07:23
@stefanprodan I don't think the issue is a complete duplicate though. The missing service account does not explain why a deleted kustomization still shows up. While it does explain why the helmrelease is still there, the message `helmreleases deleted` is misleading. What's more, service account `dev-team` was removed from the same git commit as the helmrelease and kustomization. I would expect Flux to gracefully handle the order of deletion.

**Comment by stefanprodan** [comment] 2021-03-02 07:26
>  I would expect Flux to gracefully handle the order of deletion.

I've explained why this is not possible in #997
