### ISSUE TITLE
Kustomization gets "failed to download artifact .... dial tcp 10.100.32.193:80: i/o timeout" on eks

### ISSUE THREAD

**Issue by yershalom** [fluxcd/flux2#2309] opened 2022-01-19 10:43 UTC
### Describe the bug

Hi,

My cluster worked ok and nothing has changed, but since this morning I get from the kustomization this error:

Warning  error   32s (x2 over 9m52s)  kustomize-controller  failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz giving up after 10 attem │
│ pt(s): Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hashtar.gz": dial tcp 10.100.32.193:80: i/o timeout
We are running on EKS (v1.21.5-eks-bc4871b) and the flux version is 0.25.3.

### Steps to reproduce

1. Install flux with `flux install`
2. Running `flux bootstrap github` as we always ran.
3. kustomization is not bootstarping due to the error.

### Expected behavior

To be reconciled.

### OS / Distro

amazon-eks-node-1.21-v20220112

### Flux version

v0.25.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.15.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.19.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.20.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.20.1
✔ all checks passed

### Git provider

Github

### Additional context

2022-01-19T10:06:25.706Z info Kustomization/flux-system.flux-system - Source &#39;GitRepository/flux-system&#39; not found
2022-01-19T10:15:01.322Z error Kustomization/flux-system.flux-system - Reconciliation failed after 8m35.047835645s, next try in 10m0s failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz giving up after 10 attempt(s): Get &#34;http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz&#34;: dial tcp 10.100.32.193:80: i/o timeout
2022-01-19T10:24:21.871Z error Kustomization/flux-system.flux-system - Reconciliation failed after 8m35.056592494s, next try in 10m0s failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz giving up after 10 attempt(s): Get &#34;http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz&#34;: dial tcp 10.100.32.193:80: i/o timeout
2022-01-19T10:32:56.968Z error Kustomization/flux-system.flux-system - Reconciliation failed after 8m35.047339224s, next try in 10m0s failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz giving up after 10 attempt(s): Get &#34;http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/some_hash.tar.gz&#34;: dial tcp 10.100.32.193:80: i/o timeout
2022-01-19T10:15:01.332Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object
2022-01-19T10:24:21.920Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object
2022-01-19T10:32:56.975Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object
2022-01-19T10:07:11.279Z error GitRepository/flux-system.flux-system - unable to send event POST http://notification-controller.flux-system.svc.cluster.local/ giving up after 5 attempt(s): Post &#34;http://notification-controller.flux-system.svc.cluster.local/&#34;: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-01-19T10:07:11.279Z info GitRepository/flux-system.flux-system - Reconciliation finished in 45.451012071s, next run in 1m0s
2022-01-19T10:08:11.563Z info GitRepository/flux-system.flux-system - Reconciliation finished in 283.160756ms, next run in 1m0s
2022-01-19T10:09:11.828Z info GitRepository/flux-system.flux-system - Reconciliation finished in 263.447893ms, next run in 1m0s
2022-01-19T10:10:12.218Z info GitRepository/flux-system.flux-system - Reconciliation finished in 389.301128ms, next run in 1m0s
2022-01-19T10:11:12.470Z info GitRepository/flux-system.flux-system - Reconciliation finished in 251.860268ms, next run in 1m0s
2022-01-19T10:12:12.730Z info GitRepository/flux-system.flux-system - Reconciliation finished in 259.142234ms, next run in 1m0s
2022-01-19T10:13:12.990Z info GitRepository/flux-system.flux-system - Reconciliation finished in 259.109421ms, next run in 1m0s
2022-01-19T10:14:13.354Z info GitRepository/flux-system.flux-system - Reconciliation finished in 363.649279ms, next run in 1m0s
2022-01-19T10:15:13.600Z info GitRepository/flux-system.flux-system - Reconciliation finished in 244.614003ms, next run in 1m0s
2022-01-19T10:16:13.851Z info GitRepository/flux-system.flux-system - Reconciliation finished in 249.965457ms, next run in 1m0s
2022-01-19T10:17:59.134Z error GitRepository/flux-system.flux-system - unable to send event POST http://notification-controller.flux-system.svc.cluster.local/ giving up after 5 attempt(s): Post &#34;http://notification-controller.flux-system.svc.cluster.local/&#34;: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2022-01-19 10:50
Looks like the EKS node, where kustomize-controller is running, has its network broken, this can happen due to CNI misconfiguration, crash loop or network policies bugs in your CNI implementation.

**Comment by stefanprodan** [comment] 2022-01-19 11:12
Duplicate of https://github.com/fluxcd/flux2/discussions/2307

**Closed by stefanprodan** 2022-01-19 11:12 UTC
