### ISSUE TITLE
[ImageUpdateAutomation] formats all YAML in git repository

### ISSUE THREAD

**Issue by Sijoma** [fluxcd/flux2#650] opened 2021-01-05 21:17 UTC
Hi Flux Team,

i'm quite unsure whats causing this but the ImageAutomation which should only update the image tag where my marker is placed updates many files in the git repository. It seems to format all yaml files. Is this behaviour intended? It breaks my github action yaml where I have a multiline run command.

Changed files: **(this should only be a single file, the k8s/frontend/deployment.yaml)**
 .github/workflows/frontend-build-action.yml
+34 −50  .github/workflows/frontend-build-docker-image.yaml
+4 −7  .github/workflows/maven.yml
+20 −20  backend/k8s.yml
+4 −1  backend/micronaut-cli.yml
+1 −1  k8s/common/namespace.yaml
+3 −3  k8s/frontend/deployment.yaml
+1 −1  k8s/frontend/ingress.yaml
+2 −9  k8s/frontend/nginx.configmap.yaml
+2 −2  k8s/frontend/service.yaml

Link to Commit: https://github.com/Sijoma/food-app/commit/6c147b7cf9de2785f099a68dd0dc85a2163aed9b

**Comment by stefanprodan** [comment] 2021-01-06 10:44
Duplicate of: https://github.com/fluxcd/image-automation-controller/issues/68
Fixed in: https://github.com/fluxcd/flux2/releases/tag/v0.5.8

**Closed by stefanprodan** 2021-01-06 10:44 UTC
