### ISSUE TITLE
source controller with secondary replica is never ready

### ISSUE THREAD

**Issue by rekcah78** [fluxcd/flux2#4423] opened 2023-11-22 16:57 UTC
### Describe the bug

Hello,
My problem is:
When I do a rolling upgrade or set replica 2,
the new replica never goes into a ready state

### Steps to reproduce

I use Helm chart version 2.11.1 with value 
sourceController:
  replicas: 2

### Expected behavior

all my replicas are in ready condition

### Screenshots and recordings

source-controller-8684477644-dd7gq             1/1     Running   0          45m
source-controller-8684477644-vjqhj             0/1     Running   0          6m48s

➜  ~ k logs source-controller-8684477644-vjqhj
{"level":"info","ts":"2023-11-22T15:18:27.118Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2023-11-22T15:18:27.178Z","logger":"setup","msg":"caching of Helm index files is disabled"}
{"level":"info","ts":"2023-11-22T15:18:27.217Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2023-11-22T15:18:27.218Z","msg":"Starting server","kind":"health probe","addr":"[::]:9440"}
{"level":"info","ts":"2023-11-22T15:18:27.518Z","msg":"starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2023-11-22T15:18:27.518Z","logger":"runtime","msg":"attempting to acquire leader lease flux-system/source-controller-leader-election...\n"}

### OS / Distro

Bottlerocket OS 1.16.1

### Flux version

v2.1.2

### Flux check

➜  ~ flux check
► checking prerequisites
✔ Kubernetes 1.28.3-eks-4f4795d >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2023-11-22 17:16
This is the expected behaviour, horizontal scaling works for Flux only with sharding https://fluxcd.io/flux/installation/configuration/sharding/

**Comment by hiddeco** [comment] 2023-11-22 17:23
To explain this in more detail: the source-controller serves a HTTP endpoint to fetch the obtained Artifacts from.

If it would be marked as Ready, the Service would start routing traffic to it while there would be no files to serve.

This is also the reason why it can't scale horizontally beyond having "hot standbys" waiting to become the leader, as the Artifacts would be divided across Pods. Making a HTTP request to fetch them like a lottery ticket.

**Comment by rekcah78** [comment] 2023-11-23 10:59
Thank for explanation,
in my use case i only need hot standby pod and not need to sharding my workload.
I understand why the readiness probe must be failed to avoid the trafic on standby pod but why the liveness probe fail is the app run and try to attempting to acquire leader lease ? 
There are surely reasons if it is voluntary to do this, if you have the time I would like to know more about this.

**Comment by hiddeco** [comment] 2023-11-23 11:07
The liveness probe should work just fine, it checks the `:9440/healthz` endpoint which will return a HTTP 200 `ok` response even if it has not been selected as the leader.

**Closed** 2023-11-27 13:50 UTC
Labels: wontfix
