### ISSUE TITLE
Strange behavior with flux install

### ISSUE THREAD

**Issue by uderik** [fluxcd/flux2#2344] opened 2022-01-26 13:39 UTC
### Describe the bug

Strange behavior with flux install:

```
❯ ./flux install --version=v0.19.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.16.1
❯ ./flux install --version=0.19.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.20.1
```

if tag v0.19.1 - install 0.19.1 version
if tag 0.19.1 - install latest version
deployments label with tag 0.19.1:
app.kubernetes.io/version: 0.19.1

0.24.1.bug still present
```
❯ ./flux install --version=0.24.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.20.1
❯ ./flux install --version=v0.24.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.19.2

❯ ./flux install --version=0.24.1 --export  | grep 'app.kubernetes.io/version' | head -1
    app.kubernetes.io/version: 0.24.1
 ```

### Steps to reproduce

1. install  flux 0.24.1
2. run
```
❯ ./flux install --version=0.24.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.20.1
❯ ./flux install --version=v0.24.1 --export | grep source-controller:v
        image: ghcr.io/fluxcd/source-controller:v0.19.2

❯ ./flux install --version=0.24.1 --export  | grep 'app.kubernetes.io/version' | head -1
    app.kubernetes.io/version: 0.24.1
```

### Expected behavior

although there should be an error 

### OS / Distro

ubuntu 20.0.4

### Flux version

v0.24.1

### Flux check

❯ ./flux  check
► checking prerequisites
✗ flux 0.24.1 <0.25.3 (new version is available, please upgrade)
✔ Kubernetes 1.21.5-eks-bc4871b >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.16.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2022-01-26 13:59
Duplicate of: #1711

**Closed by stefanprodan** 2022-01-26 13:59 UTC
