### ISSUE TITLE
Behavior change when modifying environment variables

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/flux2#2262] opened 2022-01-06 05:45 UTC
### Describe the bug

I think I'm noticing another behavior change after a recent upgrade to 0.24.1 from pre-0.18 versions. While applying a number of changes to environment variables in several deployments, none were applied when committed to git. Some other, related changes were made, but resources with only env var changes were not updated. Previously, these were updated when merged into git. 

Specifically, the changes were made in a `Deployment` in `.spec.template.spec.containers[1].env[]` where entries were removed. 

I looked thru the docs and couldn't find anything about how arrays or lists are handled when a single item is removed. Does it seem that by removing the entry it's no longer managed by Flux but wasn't pruned either? Is this expected behavior?

### Steps to reproduce

Remove an environment variable from a list of other environment variables and commit to the flux source.

### Expected behavior

Reconciliation should apply the changes.

### OS / Distro

n/a

### Flux version

v0.24.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.19.14-gke.1900 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.14.1
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

GCR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2022-01-06 07:04
Duplicate of: https://github.com/fluxcd/kustomize-controller/issues/486

**Closed** 2022-01-31 10:01 UTC
