### ISSUE TITLE
Kustomization and HelmRelease objects are stuck if they fail to apply on first install

### ISSUE THREAD

**Issue by drazul** [fluxcd/flux2#1577] opened 2021-07-01 09:26 UTC
### Describe the bug

Kustomization and HelmRelease objects can't be updated/deleted if they fail to be applied into the cluster when they are configured for first time.

### To Reproduce

Steps to reproduce the behaviour:

1. Install a HelmRelease to create a pod with a wrong configuration to prevent kubernetes creates the pod (bad node selector, bigger resource requests than allow,  not allowed PodSecurityPolicy). Install kustomization to apply a bad git repository, with duplicated resources or resources using a non installed CRD.
2. Delete or update the objects to fix detected issues

### Expected behavior

The object should be deleted/updated and cancel stuck reconciliation process. The same process is working on flux v1 with almost no delay.

### Additional context

There are no logs until the HR is eventually deleted (30 minutes after I deleted in my latest try)

Logs from Helm-controller when the HR is deleted (I rewrote the HR and namespace names)
```
{"level":"error","ts":"2021-07-01T09:17:24.183Z","logger":"controller.helmrelease","msg":"unable to update status after reconciliation","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"my-release","namespace":"my-namespace","error":"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"my-release\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":"2021-07-01T09:17:24.183Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"my-release","namespace":"my-namespace","error":"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"my-release\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"info","ts":"2021-07-01T09:17:24.503Z","logger":"controller.helmrelease","msg":"uninstalled Helm release for deleted resource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"my-release","namespace":"my-namespace"}
{"level":"info","ts":"2021-07-01T09:17:24.535Z","logger":"controller.helmrelease","msg":"uninstalled Helm release for deleted resource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"my-release","namespace":"my-namespace"}
{"level":"error","ts":"2021-07-01T09:17:24.540Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"my-release","namespace":"my-namespace","error":"Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"my-release\": StorageError: invalid object, Code: 4, Key: /registry/helm.toolkit.fluxcd.io/helmreleases/my-namespace/my-release, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 74bcb564-45b8-401a-b3a2-f3267b2b2ac1, UID in object meta: "}
```

$ flux check
```
► checking prerequisites
✔ kubectl 1.21.2 >=1.18.0-0
✔ Kubernetes 1.21.2 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.2
✔ all checks passed
```

**Comment by hiddeco** [comment] 2021-07-01 09:50
This is likely due to our current simple approach of patching the status, and how this at present can cause conflicts if the resource changed. We are working on a set of helpers, including one that is capable of performing patch operations while resolving conflicts, that will be rolled out across controllers to tackle this issue once and for all in the foreseeable future.

**Comment by stefanprodan** [comment] 2021-07-01 10:15
I don't see how a Kustomization can get stuck, can you please post here an example.

**Comment by drazul** [comment] 2021-07-01 10:21
@stefanprodan I broke the kustomization applying a bad git repository.

In my case I fail to migrate the HelmRelease from fluxv1 CRD (I set a wrong chart definition) and the kustomization was failing to apply all resources from the repository.

Kustomization object was alsy trying to apply same git changeset all the time, even after I fixed it and GitRepository object was already synced with the new version.

**Comment by stefanprodan** [comment] 2021-07-01 11:58
> Kustomization object was alsy trying to apply same git changeset all the time, even after I fixed it and GitRepository object was already synced with the new version.

Yes that how Flux works, it applies the latest revision at the specified interval.

**Comment by drazul** [comment] 2021-07-01 12:06
@stefanprodan but I saw the new changeset was not applied by kustomization, because it was stuck in the previous broken changeset.

To clarify the bug, I only found this weird behaviour when I create an object (HelmRelease or Kustomization) and it can't be applied properly **on the first sync**. But if I introduce a breaking change in a new commit then kustomization, or HelmRelease is marked as failed and they recover properly in the next commit.

**Comment by stefanprodan** [comment] 2021-07-01 12:23
There is no special handling for the first time a Kustomization is reconciled. it should recover when you push a fix to Git and the `Kustomization.spec.timeout` expires, it will apply the fix.

**Comment by drazul** [comment] 2021-07-01 14:15
mmm, I tried to reproduce the error with kustomization but I'm not able to do it right now. It was maybe something else... But at some point I needed to remove the kustomization object removing the finalizer... I think it could be because it was stucked waiting for HR deletion... and they was stucked

**Comment by stefanprodan** [comment] 2021-07-01 14:29
Unlike flux v1, the kustomize-controller garbage collector does not block on finalizers, and all operations performed by the controller respect the spec.timeout. If you can reproduce a stuck Kustomization I would love to see it.  I can’t rule out a bug of course, but since I wrote most of that code, I’m confident that “foever stuck” is not possible 😄.

**Comment by trathailoi** [comment] 2021-08-02 09:03
The same to me. The kustomization is stuck everytime there's something wrong with the helmrelease or helmchart. And I have to delete the kustomization object, then it will be re-created with the latest git changes afterward.
I tried to leave it to do the self-healing things. And there is no changes after a night, seem to be forever, I would say. :(

**Comment by stefanprodan** [comment] 2021-08-02 09:10
> The kustomization is stuck everytime there's something wrong with the helmrelease or helmchart.

What does this mean? Please provide some outputs:
- `flux get all`
- `flux logs --kind Kustomization --all-namespaces`

**Comment by trathailoi** [comment] 2021-08-02 09:31
sorry I was not detailed, here's the logs:
- `flux get all`
As you can see the REVISION of the `kustomization/apps` is not the latest. And it keep being like that, being stuck with that revision, no matter how many time I push new changes to the git repo. :(
```
NAME                         	READY	MESSAGE                                                        	REVISION                                     	SUSPENDED 
gitrepository/flux-system    	True 	Fetched revision: main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	False    	
gitrepository/mazi-helm-chart	True 	Fetched revision: main/437f420ba47fc3cf68be3a125616d0120d71962b	main/437f420ba47fc3cf68be3a125616d0120d71962b	False    	

NAME                               	READY	MESSAGE                                                   	REVISION                                	SUSPENDED 
helmrepository/bitnami             	True 	Fetched revision: d858e12157be8adc96b1fc341fc7b03dd97716e1	d858e12157be8adc96b1fc341fc7b03dd97716e1	False    	
helmrepository/ingress-nginx       	True 	Fetched revision: 0dc05cdaabaf7a28bcaf6f1e253dc9945953ba65	0dc05cdaabaf7a28bcaf6f1e253dc9945953ba65	False    	
helmrepository/jetstack            	True 	Fetched revision: 4874e8988397219c829eed87e1a3dcd34f392c22	4874e8988397219c829eed87e1a3dcd34f392c22	False    	
helmrepository/prometheus-community	True 	Fetched revision: 4b7d43d7bcb91780f6fce40120c85716e7cadbb3	4b7d43d7bcb91780f6fce40120c85716e7cadbb3	False    	
helmrepository/prometheus-msteams  	True 	Fetched revision: 62b7acf1e5fae2210e236c2f0cccd0c144718e84	62b7acf1e5fae2210e236c2f0cccd0c144718e84	False    	

NAME                                   	READY	MESSAGE                             	REVISION	SUSPENDED 
helmchart/cert-manager-cert-manager    	True 	Fetched revision: v1.4.1            	v1.4.1  	False    	
helmchart/mazi-mazi                    	True 	Fetched and packaged revision: 1.4.1	1.4.1   	False    	
helmchart/monitoring-prometheus        	True 	Fetched revision: 17.0.2            	17.0.2  	False    	
helmchart/monitoring-prometheus-msteams	True 	Fetched revision: 1.3.0             	1.3.0   	False    	
helmchart/nginx-nginx                  	True 	Fetched revision: 3.34.0            	3.34.0  	False    	

NAME                        	READY  	MESSAGE                                                        	REVISION                                     	SUSPENDED 
kustomization/apps          	Unknown	reconciliation in progress                                     	main/51bd7917571dfd4d258469290ebee3fb8c446360	False    	
kustomization/flux-system   	True   	Applied revision: main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	False    	
kustomization/infrastructure	True   	Applied revision: main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	main/50a0edd79cd0710b1ce48dfe6aad5cd745075514	False    	

NAME            	READY	MESSAGE     
provider/msteams	True 	Initialized	

NAME                	READY	MESSAGE    	SUSPENDED 
alert/on-call-webapp	True 	Initialized	False
```
- `flux logs --kind Kustomization --all-namespaces`
```
2021-08-02T09:13:30.618Z info Kustomization - Starting EventSource 
2021-08-02T09:13:30.618Z info Kustomization - Starting EventSource 
2021-08-02T09:13:30.618Z info Kustomization - Starting EventSource 
2021-08-02T09:13:30.618Z info Kustomization - Starting Controller 
2021-08-02T09:13:30.720Z info Kustomization - Starting workers 
2021-08-02T09:13:34.237Z info Kustomization/flux-system.flux-system - Source &#39;GitRepository/flux-system&#39; not found 
2021-08-02T09:13:59.398Z info Kustomization/apps.flux-system - Dependencies do not meet ready condition, retrying in 30s 
2021-08-02T09:13:59.465Z info Kustomization/flux-system.flux-system - Kustomization applied in 951.724423ms 
2021-08-02T09:13:59.484Z info Kustomization/flux-system.flux-system - Reconciliation finished in 3.125013693s, next run in 10m0s 
2021-08-02T09:14:01.269Z info Kustomization/infrastructure.flux-system - Kustomization applied in 843.122834ms 
2021-08-02T09:14:01.285Z info Kustomization/infrastructure.flux-system - Reconciliation finished in 1.875950801s, next run in 10m0s 
2021-08-02T09:14:29.402Z info Kustomization/apps.flux-system - All dependencies are ready, proceeding with reconciliation 
2021-08-02T09:14:30.229Z info Kustomization/apps.flux-system - Kustomization applied in 420.843043ms 
2021-08-02T09:14:30.278Z info Kustomization/apps.flux-system - Reconciliation finished in 875.73692ms, next run in 10m0s 
2021-08-02T09:21:59.069Z info Kustomization/apps.flux-system - All dependencies are ready, proceeding with reconciliation 
2021-08-02T09:22:02.973Z info Kustomization/apps.flux-system - Kustomization applied in 1.405555566s 
2021-08-02T09:22:03.379Z info Kustomization/infrastructure.flux-system - Kustomization applied in 1.890424569s 
2021-08-02T09:22:03.395Z info Kustomization/infrastructure.flux-system - Reconciliation finished in 4.326177984s, next run in 10m0s 
2021-08-02T09:22:03.616Z info Kustomization/flux-system.flux-system - Kustomization applied in 1.94469143s 
2021-08-02T09:22:03.630Z info Kustomization/flux-system.flux-system - Reconciliation finished in 4.560881019s, next run in 10m0s 
2021-08-02T09:23:36.024Z info Kustomization/flux-system.flux-system - Kustomization applied in 726.728365ms 
2021-08-02T09:23:36.037Z info Kustomization/flux-system.flux-system - Reconciliation finished in 1.79892492s, next run in 10m0s 
2021-08-02T09:24:02.857Z info Kustomization/infrastructure.flux-system - Kustomization applied in 553.897827ms 
2021-08-02T09:24:02.869Z info Kustomization/infrastructure.flux-system - Reconciliation finished in 1.580928554s, next run in 10m0s 
2021-08-02T09:13:59.401Z info Kustomization/apps.flux-system - Discarding event, no alerts found for the involved object 
2021-08-02T09:13:59.469Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object 
2021-08-02T09:13:59.485Z info Kustomization/flux-system.flux-system - Discarding event, no alerts found for the involved object 
2021-08-02T09:14:01.270Z info Kustomization/infrastructure.flux-system - Dispatching event: helmrelease.helm.toolkit.fluxcd.io/prometheus created
clusterrolebinding.rbac.authorization.k8s.io/elasticsearch-logging configured
clusterrolebinding.rbac.authorization.k8s.io/fluentd-es configured
gitrepository.source.toolkit.fluxcd.io/mazi-helm-chart created
helmrepository.source.toolkit.fluxcd.io/prometheus-community created
secret/gh-https-credentials created
statefulset.apps/elasticsearch-logging configured
helmrelease.helm.toolkit.fluxcd.io/cert-manager created
helmrepository.source.toolkit.fluxcd.io/prometheus-msteams created
deployment.apps/kibana-logging configured
ingress.extensions/logging-ingress configured
helmrelease.helm.toolkit.fluxcd.io/nginx created
helmrepository.source.toolkit.fluxcd.io/bitnami created
alert.notification.toolkit.fluxcd.io/on-call-webapp created
provider.notification.toolkit.fluxcd.io/msteams created
helmrepository.source.toolkit.fluxcd.io/ingress-nginx created
Warning: extensions/v1beta1
helmrelease.helm.toolkit.fluxcd.io/prometheus-msteams created
helmrepository.source.toolkit.fluxcd.io/jetstack created
 
2021-08-02T09:14:01.286Z info Kustomization/infrastructure.flux-system - Dispatching event: Update completed 
2021-08-02T09:14:30.231Z info Kustomization/apps.flux-system - Dispatching event: helmrelease.helm.toolkit.fluxcd.io/mazi created
 
2021-08-02T09:14:30.241Z info Kustomization/apps.flux-system - Dispatching event: Health check passed 
2021-08-02T09:14:30.279Z info Kustomization/apps.flux-system - Dispatching event: Update completed 
2021-08-02T09:22:02.979Z info Kustomization/apps.flux-system - Dispatching event: helmrelease.helm.toolkit.fluxcd.io/mazi configured
namespace/mazi configured
secret/mz-secret configured
 
2021-08-02T09:22:03.381Z info Kustomization/infrastructure.flux-system - Dispatching event: clusterrolebinding.rbac.authorization.k8s.io/fluentd-es configured
deployment.apps/kibana-logging configured
ingress.extensions/logging-ingress configured
helmrepository.source.toolkit.fluxcd.io/bitnami configured
statefulset.apps/elasticsearch-logging configured
helmrepository.source.toolkit.fluxcd.io/prometheus-community configured
helmrepository.source.toolkit.fluxcd.io/prometheus-msteams configured
helmrepository.source.toolkit.fluxcd.io/ingress-nginx configured
helmrepository.source.toolkit.fluxcd.io/jetstack configured
clusterrolebinding.rbac.authorization.k8s.io/elasticsearch-logging configured
Warning: extensions/v1beta1
 
2021-08-02T09:22:03.396Z info Kustomization/infrastructure.flux-system - Dispatching event: Update completed 
2021-08-02T09:22:03.617Z info Kustomization/flux-system.flux-system - Dispatching event: deployment.apps/source-controller configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
service/webhook-receiver configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
service/notification-controller configured
deployment.apps/kustomize-controller configured
kustomization.kustomize.toolkit.fluxcd.io/flux-system configured
namespace/flux-system configured
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
service/source-controller configured
gitrepository.source.toolkit.fluxcd.io/flux-system configured
serviceaccount/kustomize-controller configured
serviceaccount/notification-controller configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
serviceaccount/helm-controller configured
deployment.apps/helm-controller configured
networkpolicy.networking.k8s.io/allow-webhooks configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
clusterrole.rbac.authorization.k8s.io/crd-controller-flux-system configured
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system configured
networkpolicy.networking.k8s.io/allow-scraping configured
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
networkpolicy.networking.k8s.io/allow-egress configured
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
deployment.apps/notification-controller configured
clusterrolebinding.rbac.authorization.k8s.io/crd-controller-flux-system configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
serviceaccount/source-controller configured
 
2021-08-02T09:22:03.631Z info Kustomization/flux-system.flux-system - Dispatching event: Update completed 
```

**Comment by stefanprodan** [comment] 2021-08-02 09:59
Have you added health checks to the `apps` Kustomization? Can you post here `kubectl -n flux-system get kustomization apps -oyaml`

**Comment by trathailoi** [comment] 2021-08-02 10:01
sure, here is the logs.
- `kubectl -n flux-system get kustomization apps -oyaml`
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{"kustomize.toolkit.fluxcd.io/checksum":"2f064837dbb3c01be4f28bb971b8a701ba0a79f6"},"labels":{"kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"apps","namespace":"flux-system"},"spec":{"dependsOn":[{"name":"infrastructure"}],"healthChecks":[{"apiVersion":"helm.toolkit.fluxcd.io/v1beta1","kind":"HelmRelease","name":"mazi","namespace":"mazi"}],"interval":"10m0s","path":"./apps/staging","prune":true,"sourceRef":{"kind":"GitRepository","name":"flux-system"},"validation":"client"}}
    kustomize.toolkit.fluxcd.io/checksum: 2f064837dbb3c01be4f28bb971b8a701ba0a79f6
  creationTimestamp: "2021-08-02T09:13:59Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: apps
  namespace: flux-system
  resourceVersion: "2695513"
  uid: 89045a55-0d15-4cc8-a1f9-bf70a4f85b6f
spec:
  dependsOn:
  - name: infrastructure
  force: false
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v1beta1
    kind: HelmRelease
    name: mazi
    namespace: mazi
  interval: 10m0s
  path: ./apps/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
status:
  conditions:
  - lastTransitionTime: "2021-08-02T09:52:07Z"
    message: reconciliation in progress
    reason: Progressing
    status: Unknown
    type: Ready
  - lastTransitionTime: "2021-08-02T09:32:03Z"
    message: HealthCheckFailed
    reason: HealthCheckFailed
    status: "False"
    type: Healthy
  lastAppliedRevision: main/51bd7917571dfd4d258469290ebee3fb8c446360
  lastAttemptedRevision: main/50a0edd79cd0710b1ce48dfe6aad5cd745075514
  observedGeneration: 1
  snapshot:
    checksum: e25944373572eecbed2b6de8643d80bcefba714d
    entries:
    - kinds:
        /v1, Kind=Namespace: Namespace
      namespace: ""
    - kinds:
        /v1, Kind=Secret: Secret
        helm.toolkit.fluxcd.io/v2beta1, Kind=HelmRelease: HelmRelease
      namespace: mazi
```

**Comment by stefanprodan** [comment] 2021-08-02 10:06
Ok so this is a side-effect of a HelmRelease failing, you should set `spec.timeout` to a lower value than `10m` so that the Kustomization doesn't wait that long after the HelmRelease. Just to be clear, this is not a Kustomization issue, but a Helm one, the kustomize-controller uses `spec.interval` when `spec.timeout` is not set, thus giving the impression that the reconciliation is stuck, when in fact it goes from failure to reconciling instantly due to the timeout being the same as the reconciliation interval.

**Comment by trathailoi** [comment] 2021-08-02 10:23
yes, I know that it is not a Kustomization issue, because I know where the root cause is. Just the behaviour of the kustomization, it's kinda stressing me out 😄, all I can do is just deleting it, or sometime I have to `flux uninstall` and bootstrap again 😢.
By the way, could you please point out where should I put the `spec.timeout` value you was saying about? TYIA.

**Comment by trathailoi** [comment] 2021-08-02 10:26
is this correct ?
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: mazi
      namespace: mazi
```

**Comment by trathailoi** [comment] 2021-08-02 10:47
It works! Thank you so much! 🤟

**Comment by superherointj** [comment] 2021-08-14 03:30
I was having a similar issue, the workaround of `flux uninstall` and `repeat bootstrap process` worked for me. Thanks for mentioning it.

**Comment by pkit** [comment] 2021-09-27 10:44
> I don't see how a Kustomization can get stuck, can you please post here an example.

Easy: circular dependency
Both kustomizations that circularly depend on each other will output:
`Dependencies do not meet ready condition` and do it forever
And there is no way to reconcile it.
If you delete one dependency it will still try to reconcile indefinitely.

**Comment by BertelBB** [comment] 2021-11-05 15:50
One issue that comes up often in our development environments is HelmReleases ending up in a broken state because the `helm-controller` fails to reconcile it multiple times. There seems to be some threshold for how many times it can fail before the `helm-controller` simply starts ignoring it (it seems).

The only solution that I have found to remediate this problem is to delete the HelmRelease. I've never had an issue with deleting them, although sometimes it can take a while.

**Comment by hiddeco** [comment] 2021-11-05 18:36
The threshold is configurable, see:

- https://fluxcd.io/docs/components/helm/helmreleases/#configuring-failure-remediation
- https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.InstallRemediation
- https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.UpgradeRemediation

**Closed** 2023-11-24 08:52 UTC

**Comment by jmsariron** [comment] 2024-04-19 10:30
I'm kinda getting this problem still, if trying to apply a helmrelease with invalid config, the kustomization gets on a "Unkown" state and stuck with "Reconciliation in progress", if I try to force a reconciliation from the CLI tool to update the helmrelease with the fix, the cli gets stuck and the kustomization keeps stuck on the unkown state on the cluster.

I'm not sure of what is the correct fix from this thread

**Comment by onedr0p** [comment] 2024-04-19 10:56
Try adjusting your flux kustomization timeouts interval and retryInterval, another thing that helps is disable any healthchecks and set wait to false in the flux kustomization too.

**Comment by r4j4h** [comment] 2024-08-30 01:42
FWIW also try suspending and resuming the resource. I've found this to consistently get a real retry, while just reconciling the resource immediately bails like its cached the error and doesn't get a retry. It is also safer incase the resource deletion causes the controller to actually execute a "helm uninstall" under the hood or something.
