### ISSUE TITLE
Allow listing suspended kustomizations

### ISSUE THREAD

**Issue by jflambert** [fluxcd/flux2#4730] opened 2024-04-17 12:59 UTC
I am spinning off a discussion into an issue. There is no easy way for the flux command to display only suspended resources. In turn this impacts monitoring tools like `k9s` which can't (easily?) display suspended status as a column in its output.

Meanwhile, the following works well enough (as long as the output doesn't change in future flux versions!)

`flux get kustomizations | awk '{ if ( $3 == "True" ) { printf "* %s\n", $1 } }'`

_Originally posted by @jflambert in https://github.com/fluxcd/flux2/discussions/2494#discussioncomment-8551220_

**Comment by stefanprodan** [comment] 2024-04-17 21:15
Duplicate of #3886

**Closed by stefanprodan** 2024-04-17 21:15 UTC
