### ISSUE TITLE
unexpected EOF 

### ISSUE THREAD

**Issue by felix-hxz** [fluxcd/flux2#1174] opened 2021-03-29 09:03 UTC
[root@iZhp3hfhvqk4ss7gbkx4gxZ ~]# flux check --pre
► checking prerequisites
✔ kubectl 1.19.4 >=1.18.0-0
✔ Kubernetes 1.19.4 >=1.16.0-0
✔ prerequisites checks passed

[root@iZhp3hfhvqk4ss7gbkx4gxZ ~]# flux bootstrap github \
>   --owner=felix-hxz  \
>   --repository=fleet-infra \
>   --branch=main \
>   --path=./clusters/my-cluster \
>   --personal
► connecting to github.com
✔ repository created
✗ git clone error: Get "https://github.com/felix-hxz/fleet-infra/info/refs?service=git-upload-pack": unexpected EOF

**Comment by stefanprodan** [comment] 2021-03-29 09:12
Looks GitHub is having an outage, our e2e tests are failing also.

**Comment by stefanprodan** [comment] 2021-04-01 07:48
Closing this as I can't reproduce it.

**Closed by stefanprodan** 2021-04-01 07:48 UTC
