### ISSUE TITLE
Flux in AUR gives "One or more files did not pass the validity check!"

### ISSUE THREAD

**Issue by sseneca** [fluxcd/flux2#4109] opened 2023-07-29 13:10 UTC
### Describe the bug

Trying to upgrade `flux-bin` to 2.0.1-1, it doesn't work:

```
==> Making package: flux-bin 2.0.1-1 (Sat 29 Jul 2023 14:09:05 BST)
==> Retrieving sources...
  -> Found flux-bin-2.0.1.tar.gz
==> Validating source_x86_64 files with sha256sums...
    flux-bin-2.0.1.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'flux-bin-2.0.1-1': 
error: packages failed to build: flux-bin-2.0.1-1
```

### Steps to reproduce

1. paru -S flux-bin

### Expected behavior

it should install flux

### OS / Distro

arch linux

### Flux version

trying to go from 2.0.0rc.5-1 -> 2.0.1-1

### Flux check

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FabioLolix** [comment] 2023-08-09 11:03
Can't reproduce.

```
$ sha256sum flux-bin-2.0.1.tar.gz
bff7a54421a591eaae0c13d1f7bd6420b289dd76d0642cb3701897c9d02c6df7  flux-bin-2.0.1.tar.gz
```

But the pkgbuild could be improved

**Comment by relu** [comment] 2023-08-10 18:37
> But the pkgbuild could be improved

@FabioLolix would you mind creating an issue in GitHub with your recommendation from AUR? Those make a lot of sense and would be great improvements. Thank you!

**Comment by ohdearaugustin** [comment] 2023-08-21 05:00
Had the same issue with yay trying to upgrade from 2.0.0rc.5-1 to 2.0.1-1. For me cleaning the cache with ```yay -Scc``` resolved the problem.

**Comment by relu** [comment] 2023-09-08 08:09
Since it appears a solution has been found, I'm closing this issue.

**Closed by relu** 2023-09-08 08:09 UTC
