### ISSUE TITLE
Add Cross-type Dependencies

### ISSUE THREAD

**Issue by jared-schmidt-civ** [fluxcd/flux2#956] opened 2021-02-19 23:22 UTC
### Describe the bug

Currently, it is not possible to make a HelmRelease dependent on a Kustomization object or vice versa.  Adding some way of making that possible would be a big improvement to the functionality of Flux2.

### Expected behavior

A dependsOn entry could look like this:

- name: myDeployment
  namespace: myNamespace
  type: helmrelease
- name: myOtherDeployment
  namespace: myOtherNamespace
  type: kustomization

You could even loosen it up a little and allow type values of "helm, helmrelease, hr, kustomization, ks, kustomize"

**Comment by kingdonb** [comment] 2021-02-19 23:40
This was addressed in a recent discussion, it is not supported will never be, because of the complexities that could arise building interfaces that depend on arbitrary other potentially as of yet undeclared interfaces. And moreover it is not needed.

https://github.com/fluxcd/flux2/discussions/730

Thanks to the health assessment feature, you actually don't need this, I hope I can show that.

A HelmRelease can be "depended on" by a Kustomization that installs it into the cluster, in the form of the [Health Assessment](https://toolkit.fluxcd.io/components/kustomize/kustomization/#health-assessment) which can thankfully inventory the health statuses of many different object types that implement a kstatus interface to readiness and healthiness.

A HelmRelease cannot logically depend on a Kustomization in similar fashion, but since a HelmRelease (`n`) is applied to the cluster by Kustomization (`m`), there's an easy solution you might have overlooked. If, say, `n` should demand another kustomization (`l`) must be installed first, it is listed as a dependency of `m` with the same logical effect.

Eg. `(l) -> (m) -> (n)`, so transitively this way `n` depends on `l`, achieving the desired effect.

**Comment by stefanprodan** [comment] 2021-02-20 08:04
Duplicate of: #730

**Closed by stefanprodan** 2021-02-20 08:04 UTC
