### ISSUE TITLE
flux check --pre command failing

### ISSUE THREAD

**Issue by donofriov** [fluxcd/flux2#950] opened 2021-02-19 12:36 UTC
### Describe the bug

`flux check --pre` command is failing even though the prerequisites are met. 

I believe this may be failing because I am using AWS EKS and the Kubernetes version that is returned is not in true semver format, it has additional info appended to it. 

### To Reproduce

Steps to reproduce the behaviour:

1. Provide Flux install instructions

```
❯ brew install fluxcd/tap/flux
...
🍺  /usr/local/Cellar/flux/0.8.1: 3 files, 48.7MB, built in 4 seconds

❯ flux check --pre
► checking pre-requisites
✔ kubectl 1.20.2 >=1.18.0
✗ Kubernetes version must be >=1.16.0

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Note: **GitVersion:"v1.18.9-eks-d1db3c"**

2. Provide a GitHub repository with Kubernetes manifests

I'm unable to complete this step because our repositories are private.

### Expected behavior

I'd expect `flux check --pre` to succeed as all of the requirements have been met. 

### Additional context

No additional context as I haven't been able to begin the migration from v1 to v2 yet because the pre-check is failing.

**Comment by hiddeco** [comment] 2021-02-19 13:21
Duplicate of #947 fixed in #949. Will be included in the next PATCH release, until then, it is safe to continue using `flux` even while `flux check --pre` fails.

**Closed by hiddeco** 2021-02-19 13:21 UTC

**Comment by donofriov** [comment] 2021-02-19 13:25
Ah sorry I didn't see that in my search, thanks @hiddeco !

**Comment by hiddeco** [comment] 2021-02-19 13:36
@donofriov patch release is now available :-)

**Comment by donofriov** [comment] 2021-02-19 13:48
Looks good, thanks!!

```
❯ brew upgrade fluxcd/tap/flux
==> Upgrading fluxcd/tap/flux 0.8.1 -> 0.8.2
🍺  /usr/local/Cellar/flux/0.8.2: 3 files, 48.7MB, built in 4 seconds

❯ flux check --pre
► checking prerequisites
✔ kubectl 1.20.2 >=1.18.0-0
✔ Kubernetes 1.18.9-eks-d1db3c >=1.16.0-0
✔ prerequisites checks passed
```
