### ISSUE TITLE
Add "comment" arg to flux suspend

### ISSUE THREAD

**Issue by ashum81** [fluxcd/flux2#4420] opened 2023-11-22 05:33 UTC
I suggest adding a "comment" argument to the flux suspend command.
In this comment you can specify the reason why the resource was suspended, e.g. task number.
This is convenient to use in large teams.

The value of the "comment" field can be added to a resource as an annotation and removed during resume.

There is a similar command in puppet. It is very convenient in practice. And it is missing in flux.
```
puppet agent --disable "<MESSAGE>"
puppet agent --enable
```

**Comment by hiddeco** [comment] 2023-11-22 06:15
Duplicate of #4232

**Closed** 2023-11-22 06:35 UTC
