### ISSUE TITLE
custom port is not honored for ssh based git url

### ISSUE THREAD

**Issue by sartsj** [fluxcd/flux2#3045] opened 2022-08-28 22:19 UTC
I am trying to do a bootstrap of flux on to a new cluster, but the git server I have uses a custom port for its ssh access, and flux bootstrap seems to strip the port off, causing the initial clone to fail.

I found the line in the git bootstrap below, which seems to have actually been changed in the past so custom ports are allowed for http/s.

Not sure whether this is intended for ssh (I don't see why), but perhaps this can be changed. I would have done the change myself but I don't know whether there is a reason it is this way now.

https://github.com/fluxcd/flux2/blob/18c944d18a6272e4c6fb26116a9db02ba4deb937/cmd/flux/bootstrap_git.go#L190

**Comment by snebel29** [comment] 2022-08-29 14:24
@sartsj 

I do not known the full background for stripping out the port in non HTTP/HTTPS URL schemas, but I took a look around and I wonder, have you try to work around by setting `--ssh-hostname` flag?

https://github.com/fluxcd/flux2/blob/e79b008878f292cde38a276dde3415faf75ccccb/cmd/flux/bootstrap_git.go#L187-L191

The code seems to be using that flag value (without stripping out the port) as hostname on SSH URLs to replace previous hostname values, here.

https://github.com/fluxcd/flux2/blob/e79b008878f292cde38a276dde3415faf75ccccb/cmd/flux/bootstrap_git.go#L210-L213

**Comment by stefanprodan** [comment] 2022-08-29 14:39
The `--ssh-hostname` flag can contain the custom port.

**Comment by sartsj** [comment] 2022-08-29 14:58
I have tried it with --ssh-hostname

`flux bootstrap git --url=ssh://git@example.domain:30022/example/repo.git --branch=main --ssh-hostname=example.domain:30022`

unfortunately has the exact same outcome as

`flux bootstrap git --url=ssh://git@example.domain:30022/example/repo.git --branch=main`

I can probably just switch to using https, but I dont think this is working the way you think it should.

**Comment by snebel29** [comment] 2022-08-29 15:25
@stefanprodan I would gladly take a look to this issue report if you do not mind?

@sartsj would you mind confirming what version of flux are you running?

**Comment by sartsj** [comment] 2022-08-29 15:29
@snebel29 Thanks, it is version 0.32.0

**Comment by snebel29** [comment] 2022-08-29 18:43
@sartsj

Can you share the exact steps to reproduce your issue and the details on the error that you are getting back?

I just checked `v0.32.0` then build and ran the following commands, both successfully bootstrapping the repository exposed on port 29418.

```shell
$ bin/flux --verbose bootstrap git --url=ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git --branch=main --ssh-hostname=gitlab.mydomain.net:29418
```

```shell
$ bin/flux --verbose bootstrap git --url=ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git --branch=main
```

It is worth to mention that since there is no `--token-auth` flag enabled, the line that you shared on your first comment (the one that strip the port off) is not being executed, see:

https://github.com/fluxcd/flux2/blob/f2d749069e3fb4f33a6d0b8e7c66cd758bc6ae30/cmd/flux/bootstrap_git.go#L179

**Comment by sartsj** [comment] 2022-08-29 19:36
@snebel29 The error I'm getting is an ssh 'key is unknown' error because I actually end up on the wrong server. My port 30022 is a nodeport service in a kubernetes cluster, so in this case flux will actually connect to 22 of the kubernetes node instead of the nodeport service on 30022.

In your test setup, do you happen to ALSO have port 22 opened as normal? If so, I imagine you will not notice an error.

**Comment by snebel29** [comment] 2022-08-29 20:19
@sartsj 

> In your test setup, do you happen to ALSO have port 22 opened as normal? If so, I imagine you will not notice an error.

At the beginning of my test I confirmed that the destination port I was connecting to was `29418`, in my Mac:
```shell
$ netstat -p tcp -van |grep 29418
tcp4       0     36  X.X.X.X.65000   Y.Y.Y.Y.29418      ESTABLISHED 131072 132104  40051      0 0x0102 0x00000008
```

I think it is worth double checking in your side

- That your SSH setup is correct, for example; Are you able to pull the repository manually?
```shell
$ git clone ssh://git@example.domain:30022/example/repo.git
```
- Is your SSH identity loaded in the ssh-agent? I believe if it is not loaded you need to pass different authentication flags
```shell
$ ssh-add -L
```
For instance, I had to add it myself before flux could authenticate
```
$ bin/flux bootstrap git --url=ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git --branch=main
► cloning branch "main" from Git repository "ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git"
✗ failed to clone repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
```shell
$ ssh-add ~/.ssh/id_rsa
```

If you do not provide concrete steps to reproduce the error, neither other evidence (logs, screenshoots, dump, etc.) that show flux is actually hitting port 22 is going to be difficult for me to help you, as I cannot reproduce the error myself with the command lines and version that you shared.

Cheers.

**Comment by sartsj** [comment] 2022-08-29 20:43
Very odd, I'll definitely keep investigating. Thanks for your help so far. I also had a look at the code again here but I'm pretty stumped as to why this is happening.

To answer your questions:

- I've used this git server for a long time already, so I have no issue connecting to it normally. 
- Because of the above, I also know the private key is available and working.

The message I get from flux:
`✗ failed to clone repository: ssh: handshake failed: knownhosts: key is unknown`

Like I mentioned, this is just an ssh error for a wrong knownhosts key. I think this has to do with the fact that it ends up on the wrong server and thus the hostname doesn't match the server key that it had already saved to known hosts file in the past.

Additionally, what I had previously done to verify as well. I opened both git server logs and kubernetes host node auth.log at the same time. When I pull from the same repo with git myself, I see a logon on the git server. When I run flux bootstrap, I see an attempted logon on the kubernetes host.

I could provide you the logs but I'm not sure what good that would do. You would just see attempted logons.

I did try the --verbose flag on flux bootstrap but that doesn't seem to do anything?

**Comment by sartsj** [comment] 2022-08-29 21:05
Though the auth.logs of the other server already confirmed it, I did an additional check with tcpdump, and it really is connecting to port 22 instead of 30022.

**Comment by snebel29** [comment] 2022-08-30 06:16
@sartsj 

If we cannot reproduce the error I cannot help you.

Can you share?

1. The operating system where you are running flux, for example in *nix systems share the output of
```shell
$ uname -a
```
2. The output of 
```shell
$ flux --version
```
3. The full flux command with its output, for example:
```shell
$ bin/flux bootstrap git --url=ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git --branch=main
► cloning branch "main" from Git repository "ssh://git@gitlab.mydomain.net:29418/mynamespace/test.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
^C
```
4. The exact command, output and location from where you are running the command that you are using to find out what destination port flux is hitting, for example if you are running a TCPDUMP, confirm if it is the same machine that you are running flux CLI, then the exact command and output.

5. Do you have access to a fresh/isolated environment? A Virtual machine or a container would do it, can you repeat the previous steps in such environment?

Cheers.

**Comment by sartsj** [comment] 2022-08-30 12:17
Sorry, I realize very well that if you cannot reproduce it you cant help me. I will have to find a way to reproduce it.

I am not intentionally being obtuse about providing you more details. I am just not sure what you expect of the information I would be able to give you.

`Linux manjaro 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux`

The output of the flux command is literally just 2 lines, 50% of which I already provided previously:

`► cloning branch "main" from Git repository "ssh://git@git.example.tld:30022/example/repo.git"
✗ failed to clone repository: ssh: handshake failed: knownhosts: key is unknown`

Lastly, I ran tcpdump on the same machine (VM) as the flux command, i could show you the output but I would obfuscate the IPs so it wouldn't do you much good either. Trust me when I say it connects to port 22. As hard as that is to do for a random person on the internet ;)

I will see if I can reproduce it some other way.

**Comment by snebel29** [comment] 2022-08-30 14:44
@sartsj 

I wasn't suggesting that you are purposely obtuse, I am sorry if you felt that way. It is just that in order to find what is going on I need to keep a skeptical mindset, which includes what you assert seeing.

The more detailed and actionable the information that you provide about your environment is, the easier is for me to understand and to try to reproduce your issue, unfortunately for the moment without success.

I "trust" you when you say your tcpdump shows flux hitting port 22, the tcpdump however could reveal more than that, for example flux failing to handshake on 30022 then trying 22, the use of a specific interface, etc. Any additional raw information may bring value...

Another suggestion, is to look to other configuration in your system that may be interfering, Flux ENV Variables, IPTable rules, SSH config, etc.

Let me know if you find any hints.

Good luck.

**Comment by sartsj** [comment] 2022-08-30 16:01
Your last comment triggered my brain, and now I feel both like an idiot for wasting your time, but also that this is quite counter intuitive.

I realized I had added the git server to my ssh config (it wasn't in there before because I never needed it) after trying bootstrap the first time, because I was also getting an ssh error. I think it wasn't picking up my private key that time.

Unfortunately, the mistake I made here was that I forgot to add Port 30022 to the config there. As soon as I removed the whole host from my ssh config it started working.

Since it now works without the host config in there, I assume the ssh-add I did while troubleshooting fixed my earlier problem, which meant I now didnt need the ssh config anymore. But because I forgot to add the port I kept running into the problem we've been troubleshooting.

That leaves me with my remark on the counter intuitiveness of it all. Why is flux taking ssh config parameters as truth when I specifically give it all the information it needed in the command? Or is this a problem caused somewhere else by ssh?

**Comment by snebel29** [comment] 2022-08-30 19:49
> That leaves me with my remark on the counter intuitiveness of it all. Why is flux taking ssh config parameters as truth when I specifically give it all the information it needed in the command? Or is this a problem caused somewhere else by ssh?

From a quick look it seems this behaviour is inherited from the third party dependency `go-git`, see [here](https://github.com/go-git/go-git/blob/da810275bf682d29a530ed819aff175f47bd7634/plumbing/transport/ssh/common.go), I couldn't tell if this was consciously adopted, or it was accidental, without much thinking I could think of some reason to go both ways.

Also, I am not sure if you would encounter the same behaviour when forcing to run with `gitlib2`, it is in any case not documented in the difference section, [here](https://fluxcd.io/flux/components/source/gitrepositories/#git-implementation), I may give it a try tomorrow...

I hope that helps.

**Comment by snebel29** [comment] 2022-08-31 10:16
At first glance `gitlib2` dependency is not actively used in this specific repository, a git implementation can be defined using flags duriung bootstraping but that information seems to be passed down for other components to know when to use one vs the other git implementation. In a nutshell, all the flux CLI (in this repo) seems to be using `go-git` and therefore an automatic loading of `ssh_config` would happen.

My best guess is that this "feature" may have be seen as a convenience for users, but may well just have passed un-noticed.

@stefanprodan In the assumption my analysis is correct, do you feel this deserves further explanation somewhere in the documentation?

Otherwise I thin we are good to close this issue.

Cheers.

**Comment by stefanprodan** [comment] 2022-08-31 10:24
We do mention that `flux bootstrap git` is using the the SSH agent: https://fluxcd.io/flux/installation/#generic-git-server I guess it’s not obvious that this means loading the ssh config file? We could mention it explicitly then.

**Comment by sartsj** [comment] 2022-08-31 10:45
If it were me I would put an explicit warning/remark that it means that any git host info you provide to the flux command will be overridden by whatever is in your ssh config file. That way there is no ambiguity. I'm sure not everyone is aware of what it means that SSH agent is used.

**Comment by snebel29** [comment] 2022-09-05 14:34
To be clear, the `ssh-agent` has nothing to do with the fact the `go-git` implementation is loading ssh_config hostname and port when available.

I just opened a MR in the website documentation with a little warning.

**Closed** 2022-09-05 14:43 UTC
Labels: area/bootstrap
