### ISSUE TITLE
[Gitlab] flux bootstrap fails for personal projects if they already exist

### ISSUE THREAD

**Issue by IsNull** [fluxcd/flux2#835] opened 2021-01-31 15:42 UTC
When I try to update my flux v2 installation using the bootstrap command it fails with an error from gitlab:

> failed to create project, error: POST https://gitlab.com/api/v4/projects: 400

I use the below bootstrap command to install / update flux v2, which worked until now:

```bash
ubuntu@srv1:~$ cat install-flux.sh 
curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

export GITLAB_TOKEN=???????????????

flux bootstrap gitlab \
  --owner=isnull \
  --repository=myrepo \
  --branch=master \
  --path=k8 \
  --token-auth \
  --personal
```

Executing the flux bootstrap yields the error:
```bash
ubuntu@srv1:~$ sh install-flux.sh 
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.7.4 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.7.4/flux_0.7.4_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.7.4/flux_0.7.4_linux_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux
► connecting to gitlab.com
✗ failed to create project, error: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}
```

Sys info:
```bash
ubuntu@srv1:~$ flux check
► checking prerequisites
✔ kubectl 1.20.2 >=1.18.0
✔ Kubernetes 1.19.5-34+8af48932a5ef06 >=1.16.0
► checking controllers
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.5.6
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.5.3
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.4.4
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.5.0
✔ all checks passed
```

Maybe some Gitlab project api change caused this?

**Comment by IsNull** [comment] 2021-02-03 10:27
I guess the error is caused by this code which fails when the project/repo already exists. 

```go
func bootstrapGitLabCmdRun(cmd *cobra.Command, args []string) error {

// ...

	// create GitLab project if doesn't exists
	logger.Actionf("connecting to %s", gitlabArgs.hostname)
	changed, err := provider.CreateRepository(ctx, repository)
	if err != nil {
		return err
	}
	if changed {
		logger.Successf("repository created")
	}
// ...
}
```
https://github.com/fluxcd/flux2/blob/main/cmd/flux/bootstrap_gitlab.go#L154-L162

**Comment by kingdonb** [comment] 2021-02-03 13:19
To add to this report, flux bootstrap gitlab also fails if:

```
flux bootstrap gitlab --owner=$GITLAB_USER \
  --repository=fleet-infra \
  --branch=main \
  --path=./clusters/my-cluster \
  --token-auth --personal
```

in the bootstrap guide for gitlab, `--branch=main` is used to set the branch to create, but the gitlab repo is created with a default branch of `master`.

I would have thought that repeating the repo creation step through a second invocation of:

```
flux bootstrap gitlab --owner=$GITLAB_USER --repository=fleet-infra --branch=master --path=./clusters/my-cluster --token-auth --personal
```

would trigger the issue that you reported @IsNull , but I did not see it reproduced.

Can you see for sure the issue is still reproducible on Flux 0.7.6? I have tried again and cannot repro the issue you reported. I got a failure on the second try that was related to permissions on my cluster user that were too restrictive to deploy flux with these settings, and so ran "flux uninstall" before switching to a different cluster where I had more permissions

So, on the second cluster I ran again the same bootstrap command, and it had no trouble reusing the existing project/repo.

I then ran `flux uninstall` again, which had to be run a second time either because of finalizer or because I was too impatient (not sure, it worked fine the second time). I was able to repeat the bootstrap with no problem a third time. But I cannot see what is different about my execution than yours @IsNull if you can see please point it out.

**Comment by kingdonb** [comment] 2021-02-03 13:20
```
$ flux -v
flux version 0.7.6
```

**Comment by IsNull** [comment] 2021-02-03 13:28
Yes the issue still exists with the latest version. It certainly worked before.

```
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.7.6 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.7.6/flux_0.7.6_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.7.6/flux_0.7.6_linux_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux
► connecting to gitlab.com
✗ failed to create project, error: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}
```

Maybe the error message is missleading^^

* I will try to gen a new token just to be sure
* I will try to uninstall & reinstall flux again

**Comment by yebyen** [comment] 2021-02-03 13:36
There is the possibility that it is an unhelpful or obscure form of a permission error, I wasn't able to find documentation about what permissions are required for gitlab tokens either, so I have granted all permission; if you are using less permission, please note that here also.

**Comment by IsNull** [comment] 2021-02-03 13:44
The old token, which worked before, had only the `api` role. 
I have now generated a new token and tried it again, again no luck. Roles now:
`api, read_user, read_api, read_repository, write_repository, read_registry, write_registry`

**Comment by kingdonb** [comment] 2021-02-03 14:27
I wonder what else could cause `{message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}`

I will try again later, but this error almost looks as if something is being rate limited. If you can shed any new light on things that might be unique about your account leading to this error, please let us know.

**Comment by IsNull** [comment] 2021-02-03 15:00
Well I tried to install it into a different project which at least worked to a certain point, now I need to remove the old install.
But of course, flux uninstall is completely broken and does not clean up finalizers properly which leaves the namespace stuck.

This has nothing to do with the initial issue but 
```
NAME                                                    READY   STATUS                                                              AGE
kustomization.kustomize.toolkit.fluxcd.io/flux-system   True    Applied revision: master/4626aeee27447cd6d76bc27a63ef032461170e89   79d
NAME                                                 URL                                  READY   STATUS                                                              AGE
gitrepository.source.toolkit.fluxcd.io/flux-system   https://gitlab.com/isnull/myrepo   True    Fetched revision: master/4626aeee27447cd6d76bc27a63ef032461170e89   79d
```

manually removing the finalizer wont work either:

```
$ kubectl patch ns flux-system -p '{"metadata":{"finalizers":null}}';
namespace/flux-system patched (no change)
```
And then I thought kubernetes is cool :)

I will report back once I cleaned up this mess.

**Comment by kingdonb** [comment] 2021-02-03 16:08
The finalizers are on the resources themselves, not the flux-system namespace

https://github.com/fluxcd/flux2/discussions/413#discussioncomment-121453

This discussion reference should help, of course you can change it to your `flux-system` namespace

**Comment by IsNull** [comment] 2021-02-03 17:17
> The finalizers are on the resources themselves, not the flux-system namespace
The namespace has now been removed after manually patching the finalizers of kustomize and gitrepo resources.

----

* I have now bootstraped an new project which was successfully created.
* Without any modifications, if I run the bootstrap command again, it will show the same error:

```
[sudo] password for ubuntu: 
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.7.6 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.7.6/flux_0.7.6_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.7.6/flux_0.7.6_linux_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux
► connecting to gitlab.com
✗ failed to create project, error: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}
```
So its pretty much reproducible for me. I really fail to see how this can only happen on my side.  Its certainly not a permission issue.

Would it be possible to add a check before creating the Gitlab project/repo, and skipping the project creation if it already exists?

**Comment by stefanprodan** [comment] 2021-02-03 17:36
@IsNull this how we query for projects https://github.com/fluxcd/pkg/blob/main/git/provider_gitlab.go#L60 maybe the GitLab API changed? Feel free to open a PR if you have a solution to this.

**Comment by IsNull** [comment] 2021-02-03 19:21
Thanks for the pointer, as far as I can tell the check if there is an existing project is already implemented. But for some reason, there is no project returned.

The "personal" branch (which should be executed) boils down to this project search: 

```go
lpo := &gitlab.ListProjectsOptions{
			Search: gitlab.String(r.Name),
			Owned:  gitlab.Bool(true),
		}
		projects, _, err = gl.Projects.ListUserProjects(users[0].ID, lpo, gitlab.WithContext(ctx))
		if err != nil {
			return nil, nil, fmt.Errorf("failed to list projects, error: %w", err)
		}
```

I've never written any Go, but it looks pretty straightforward to me. For some reason, this call does not return the existing project and thus it attempts to  recreate it.

> maybe the GitLab API changed?

Yeah thats possible, we run some CI automation on Gitlab which uses their API and they managed to break the APIs a couple of times in the past months. I see this project is using `github.com/xanzy/go-gitlab` for the client, maybe this needs a follow up there. They have a lot of releases, does flux use the most recent version?

**Comment by IsNull** [comment] 2021-02-03 19:30
I have now tested with using the GitLab Groups (vs Personal) and with that, it works:

```
flux bootstrap gitlab \
  --owner=mygroup \
  --repository=myrepo \
  --branch=master \
  --path=k8 \
  --token-auth 

#  --personal
```
Executing it multiple times is fine. So it is an issue strictly with the personal repos.

**Comment by yebyen** [comment] 2021-02-03 19:34
My test that worked was using personal too, and also on gitlab.com saas, so I am not sure what else is different.

**Comment by IsNull** [comment] 2021-02-03 19:38
@yebyen is your personal project private as well? (vs internal or public)

**Comment by yebyen** [comment] 2021-02-03 19:42
No, public. I did not see the private flag in your build notes, if your project is private then that will probably be the difference.

**Comment by stefanprodan** [comment] 2021-02-04 10:34
> No, public. I did not see the private flag in your build notes

There is no private flag, check out the command description:

```console
 $ flux bootstrap gitlab -h

Flags:
  -h, --help                    help for gitlab
      --hostname string         GitLab hostname (default "gitlab.com")
      --interval duration       sync interval (default 1m0s)
      --owner string            GitLab user or group name
      --path safeRelativePath   path relative to the repository root, when specified the cluster sync will be scoped to this path
      --personal                is personal repository
      --private                 is private repository (default true)
      --repository string       GitLab repository name
      --ssh-hostname string     GitLab SSH hostname, to be used when the SSH host differs from the HTTPS one
```

**Comment by yebyen** [comment] 2021-02-04 11:46
I see, the private is set true by default, and my fleet infra repo is private. Then this is still back to being a mystery for now... I will try a few more times today and see if I can repro this time.

**Comment by hiddeco** [comment] 2021-02-04 12:58
Using the package we created for communicating with GitLab and other Git providers, I created a simply test to confirm the workings of the (repeated) creation of a GitLab repository.

Before running the tests, I created two groups on my personal GitHub account, one private and one public, and a new PAT with `api` scope assigned.

The following test cases all succeeded, even when run multiple times:

- Creating a _personal_ and _private_ repository
- Creating a _personal_ and _public_ repository
- Creating a _private_ repository in a _public_ group
- Creating a _private_ repository in a _private_ group
- Creating a _public_ repository in a _public_ group
- Creating a _public_ repository in a _private_ group

**Comment by hiddeco** [comment] 2021-02-04 15:42
It would be great if all the people that were experiencing issues would be able to try out the binary available at https://dl.huge.horse/flux and report back.

It contains a Linux ARM64 build of `main` + #863.

**Comment by stefanprodan** [comment] 2021-02-05 15:44
This should be fixed in flux2 v0.7.7, @IsNull please give it try.

**Comment by IsNull** [comment] 2021-02-05 16:17
Initial bootstrap worked, executing it again fails with the same error:

```bash
ubuntu@srv1:~$ cat personal_install_flux.sh 
curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

export GITLAB_TOKEN=??????????

flux bootstrap gitlab \
  --owner=isnull \
  --repository=testkube \
  --branch=master \
  --path=k8 \
  --token-auth \
  --personal

ubuntu@srv1:~$ sh personal_install_flux.sh 
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.7.7 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.7.7/flux_0.7.7_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.7.7/flux_0.7.7_linux_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux
► connecting to gitlab.com
✗ failed to create project, error: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}

```

As a workaround I have migrated my repo to a group I own, which works without any issue. Therefore, for me resolving this issue is no longer a high priority. So unless someone else can reproduce this I would be fine to close it as an oddity which only affects my account :-/

Even thought so far we could not find the root cause, I am very impressed how fast and intense you support here. Thank you! 👍

**Comment by hiddeco** [comment] 2021-02-05 17:46
@IsNull I have at this point no idea what makes your account "special". I run your script (minus the installation of `flux`) multiple times, even with a CamelCase version of my GitLab username as `--owner`, and it worked flawlessly:

```console
$ ./install-flux.sh
► connecting to gitlab.com
✔ repository created
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
...
$ ./install-flux.sh
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components are up to date
► installing components in flux-system namespace
...
$ ./install-flux.sh
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components are up to date
► installing components in flux-system namespace
...

**Closed** 2021-04-07 08:40 UTC

**Comment by taveraluis** [comment] 2021-05-22 01:46
I was stuck with this issue as well. For me, the problem was in the repository flag. I used the full string for git clone. Changing this to only the repository name **as indicated on the documentation** fixed my issue.

**Comment by tjanson** [comment] 2023-09-13 16:50
I did in fact run into this with the current version of Flux (`v2.1.0`) and GitLab (on-prem, Community Edition, `v16.2.2`). All I did was:

```shell
$ flux bootstrap gitlab --token-auth --hostname=gitlab.foo.bar --owner=tjanson --repository=flux-test --path=clusters/some-cluster --personal
# output omitted; reconciliation fails due to self-signed cert

$ flux bootstrap gitlab --token-auth --hostname=gitlab.foo.bar --owner=tjanson --repository=flux-test --path=clusters/some-cluster --personal --insecure-skip-tls-verify
Please enter your GitLab personal access token (PAT):
► connecting to https://gitlab.foo.bar
✗ failed to create new Git repository "https://gitlab.foo.bar/tjanson/flux-test": multiple errors occurred:
- POST https://gitlab.foo.bar/api/v4/projects: 400 {message: {name: [has already been taken]}, {path: [has already been taken]}, {project_namespace.name: [has already been taken]}}
- resource already exists, cannot create object. Use Reconcile() to create it idempotently
```

(Okay, there's *one* thing I did in between: I manually changed the visibility of the GitLab project - in case that's relevant.)

**Comment by Nils98Ar** [comment] 2023-11-03 09:03
For me `flux bootstrap gitlab` does not work for an existing group project with deploy-token-auth which worked in the past. Flux always tries to create the repo.

GitLab 16.5.1 and flux 2.1.2.

```
flux bootstrap gitlab --components-extra=image-reflector-controller,image-automation-controller --owner=<group> --repository=<repo> --deploy-token-auth --hostname https://gitlab.xyz.abc --path <path in repo> --branch main
► connecting to https://gitlab.xyz.abc
✗ failed to create new Git repository "https://gitlab.xyz.abc/<group>/<repo>": multiple errors occurred:
- POST https://gitlab.xyz.abc/api/v4/projects: 400 {message: {namespace: [is not valid]}}
- POST https://gitlab.xyz.abc/api/v4/projects: 400 {message: {namespace: [is not valid]}}

```

**Comment by makkes** [comment] 2023-11-03 09:59
@Nils98Ar does the token in `GITLAB_TOKEN` have access to that repository? You can verify this with this command (make sure to convert any `/` in `<group>` to `%2FA`:

```
curl -H "Authorization: Bearer $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/<group>%2F<repo>"
```

**Comment by Nils98Ar** [comment] 2023-11-03 10:11
In my case it was due to a faulty apache reverse proxy config (in front of the gitlab docker container), this one worked: https://gitlab.com/gitlab-org/gitlab/-/issues/18775#note_215017822
