### ISSUE TITLE
Failure when creating initial Kustomization 

### ISSUE THREAD

**Issue by frank-bee** [fluxcd/flux2#718] opened 2021-01-15 14:59 UTC
When I do the bootstrapping like this 
`flux create kustomization flux-system \
  --source=flux-system \
  --path="./clusters/dev" \
  --prune=true \
  --interval=10m
`

I get this type of error

✚ generating Kustomization
► applying Kustomization
✔ Kustomization updated
◎ waiting for Kustomization reconciliation
✗ failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz, error: Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz": dial tcp 10.0.186.186:80: i/o timeout

Detailed error log of the kustomize controller 
```
logs kustomize-controller-8556d55c7c-jt94p  -n flux-system 
{"level":"info","ts":"2021-01-15T14:39:32.609Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-01-15T14:39:32.609Z","logger":"setup","msg":"starting manager"}
I0115 14:39:32.611639       6 leaderelection.go:243] attempting to acquire leader lease  flux-system/7593cc5d.fluxcd.io...
I0115 14:39:32.633419       6 leaderelection.go:253] successfully acquired lease flux-system/7593cc5d.fluxcd.io
{"level":"info","ts":"2021-01-15T14:39:32.712Z","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":"2021-01-15T14:39:32.713Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-01-15T14:39:32.713Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-01-15T14:39:32.813Z","logger":"controller.kustomization","msg":"Starting EventSource","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","source":"kind source: /, Kind="}
{"level":"info","ts":"2021-01-15T14:39:32.913Z","logger":"controller.kustomization","msg":"Starting Controller","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization"}
{"level":"info","ts":"2021-01-15T14:39:32.913Z","logger":"controller.kustomization","msg":"Starting workers","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","worker count":4}
{"level":"error","ts":"2021-01-15T14:44:05.124Z","logger":"controller.kustomization","msg":"unable to send event","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"POST http://notification-controller/ giving up after 5 attempt(s): Post \"http://notification-controller/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"info","ts":"2021-01-15T14:44:05.134Z","logger":"controller.kustomization","msg":"Reconciliation finished in 1m10.033866893s, next run in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"master/c1de637b168d45b34eb10bf67ec516403be5b82a"}
{"level":"error","ts":"2021-01-15T14:44:05.134Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz, error: Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz\": dial tcp 10.0.186.186:80: i/o timeout"}
{"level":"error","ts":"2021-01-15T14:45:15.152Z","logger":"controller.kustomization","msg":"unable to send event","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"POST http://notification-controller/ giving up after 5 attempt(s): Post \"http://notification-controller/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
{"level":"info","ts":"2021-01-15T14:45:15.165Z","logger":"controller.kustomization","msg":"Reconciliation finished in 1m10.024994848s, next run in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"master/c1de637b168d45b34eb10bf67ec516403be5b82a"}
{"level":"error","ts":"2021-01-15T14:45:15.165Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz, error: Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz\": dial tcp 10.0.186.186:80: i/o timeout"}
{"level":"error","ts":"2021-01-15T14:46:25.188Z","logger":"controller.kustomization","msg":"unable to send event","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"POST http://notification-controller/ giving up after 5 attempt(s): Post \"http://notification-controller/\": dial tcp 10.0.178.64:80: i/o timeout (Client.Timeout exceeded while awaiting headers)"}
{"level":"info","ts":"2021-01-15T14:46:25.198Z","logger":"controller.kustomization","msg":"Reconciliation finished in 1m10.02315228s, next run in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"master/c1de637b168d45b34eb10bf67ec516403be5b82a"}
{"level":"error","ts":"2021-01-15T14:46:25.198Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","error":"failed to download artifact from http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz, error: Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/c1de637b168d45b34eb10bf67ec516403be5b82a.tar.gz\": dial tcp 10.0.186.186:80: i/o timeout"}

```

**Comment by hiddeco** [comment] 2021-01-15 15:01
What version of `flux` are you on?

**Comment by stefanprodan** [comment] 2021-01-15 15:04
What Kubernetes distribution are you using? what about CNI? do you have any network policies setup?

**Comment by frank-bee** [comment] 2021-01-15 15:06
I used the latest version , was just running it some minutes ago @hiddeco

**Comment by frank-bee** [comment] 2021-01-15 15:07
0.5.8

**Comment by frank-bee** [comment] 2021-01-15 15:10
the cluster is a aks (azure) one 
module "aks" {
  source                           = "Azure/aks/azurerm"
  version                          = "4.6.0"
  resource_group_name              = azurerm_resource_group.cluster.name
  kubernetes_version               = "1.19.3"
  orchestrator_version             = "1.19.3"
  network_plugin                   = "azure"
  ...

**Comment by stefanprodan** [comment] 2021-01-15 15:11
Duplicate of: #703 Update to flux 0.6.0

**Comment by frank-bee** [comment] 2021-01-15 15:12
thanks!

**Closed by stefanprodan** 2021-01-15 15:11 UTC
