### ISSUE TITLE
CLI Design Flaw: Invalid flux uninstall helmrelease Command Uninstalls Flux Resources Without Error

### ISSUE THREAD

**Issue by xsoheilalizadeh** [fluxcd/flux2#4639] opened 2024-02-29 11:03 UTC
### Describe the bug

I discovered a potentially dangerous flaw in the CLI design when an invalid command, intended to delete a HelmRelease, instead initiated the uninstallation of Flux resources from our Kubernetes cluster. This behavior is unexpected and poses a significant risk, especially in production environments, as it could inadvertently lead to the deletion of critical resources.

```
flux uninstall helmrelease vswh -n vswh
```

### Steps to reproduce

1. Run the flux uninstall helmrelease <release-name> -n <namespace> command with an invalid syntax intended for another operation.
2. Note that instead of receiving an error, the command proceeds to uninstall Flux resources.

### Expected behavior

Given the invalidity of the command (attempting to use flux uninstall for a HelmRelease deletion), I expected the CLI to return an error message indicating the command was unrecognized or improperly formatted, preventing any unintended actions.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment] 2024-02-29 12:14
Duplicate of: https://github.com/fluxcd/flux2/issues/4551

This issue was fixed in v2.2.3

**Closed by stefanprodan** 2024-02-29 12:14 UTC
